### ISSUE TITLE
Weekdays printing NA after 28 entries

### ISSUE THREAD

**Issue by vahanaslanyan** [wadpac/GGIR#100]
Hello,

Thank you for creating this tool!
I am working with GeneActive data that has 33 entries. I noticed that after 28 days of tracking , the weekday is not getting printed automatically, and some weekend/weekday based summaries are incorrect as a result. We looked up the source code and found that in g.analyze.R on line 445 weekdays were repeated only 28 times. I currently changed  that part for myself  and the function runs correctly in my namespace in R, but lifting that 28 day limit can potentially help other people that work with long tracking periods. Thank you!

**Comment by vincentvanhees** [comment]
Thanks, we will incorporate this in the next release.

**Comment by vahanaslanyan** [comment]
Thank you!
