### ISSUE TITLE
version 1.5-24 incorrect reporting of valid days

### ISSUE THREAD

**Issue by Alex-Row** [wadpac/GGIR#101]
Hi Vincent,

I’m re-processing some files I had previously analysed in GGIR1.5-21 and came across an issue with valid days in version 1.5-24:

In 1.5-24 it appears to count all days as valid. It gets the wear_duration and 24 h cycle correct, it is just the valid days number. See attached, particularly person 8.
[part2_summary_vers21.xlsx](https://github.com/wadpac/GGIR/files/2189474/part2_summary_vers21.xlsx)
[part2_summary_ver24.xlsx](https://github.com/wadpac/GGIR/files/2189475/part2_summary_ver24.xlsx)

Let me know if it would be helpful to have any meta files

Thanks,
Alex

**Comment by vincentvanhees** [comment]
thanks Alex, I will look into this

**Comment by vincentvanhees** [comment]
I have fixed it here on GitHub, and the changes will be incorporated in the next CRAN release of GGIR
