### ISSUE TITLE
Error in Math.factor(1L) : ‘round’ not meaningful for factors

### ISSUE THREAD

**Issue by KHC745** [wadpac/GGIR#108]
Hi all,
I am trying to run GGIR with sleep log data and apparently it stopped at Part 4 where this error popping up:Error in Math.factor(1L) : ‘round’ not meaningful for factors.
I guess it has something to do with the sleep log format; however, I have prepared the sleep log in csv format as per recommended in the manual and thus I am not too sure what it meant. Hopefully someone can tell me which part went wrong! Thanks!

> g.shell.GGIR(mode=c(1,2,3,4), datadir="/Users/khc745/Documents/GENEActiv analysis/Data", outputdir="/Users/khc745/Documents/GENEActiv analysis/Results", f0=1, f1=1, do.enmo = TRUE, do.anglez=TRUE, chunksize=1, printsummary=TRUE, strategy = 2, ndayswindow=6, hrs.del.start = 0,hrs.del.end = 0, maxdur = 0,includedaycrit = 10, winhr = c(5,10), qlevels = c(c(1380/1440),c(1410/1440)), qwindow=c(0,24), ilevels = c(seq(0,400,by=50),8000), timethreshold=c(5), ignorenonwear=TRUE, excludefirstlast = FALSE, includenightcrit = 16, loglocation="/Users/khc745/Documents/GENEActiv_sleeplog/sleeplog.csv", outliers.only = TRUE, criterror = 4, relyonsleeplog = TRUE, sleeplogidnum = TRUE, colid=1, coln1=2, do.visual = TRUE, nnights =6, do.report=c(2,3,4), visualreport=TRUE, dofirstpage = TRUE, viewingwindow=1)

_____________________________________________________________________________________________________________________________________________________________
Part 1

_____________________________________________________________________________________________________________________________________________________________
Part 2

_____________________________________________________________________________________________________________________________________________________________
Part 3

_____________________________________________________________________________________________________________________________________________________________
Part 4
Error in Math.factor(1L) : ‘round’ not meaningful for factors

![screen shot 2018-08-21 at 6 28 16 pm](https://user-images.githubusercontent.com/42427647/44390218-1b6f4f80-a570-11e8-8dbd-ede2da796e8c.png)

**Comment by vincentvanhees** [comment]
you probably need to use sleeplogidnum = FALSE because your identifiers seems to be in character form. 
Thanks for formulating your question so clearly!

**Comment by KHC745** [comment]
Hi Vincent,

Thank you for your quick response on this matter. I tried to use sleeplogidnum = FALSE but then there's another error coming up which I have also seen it before - not sure what it meant...
![screen shot 2018-08-27 at 9 25 19 am](https://user-images.githubusercontent.com/42427647/44634314-7fb06a00-a9db-11e8-954c-ee24cf113ee2.png)

**Comment by KHC745** [comment]
Hi Vincent,

Thank you for your prompt response. I had a look at the summary report for Part 2 and the id format is similar to the one I put in sleeplog (e.g. A02). 
![screen shot 2018-08-28 at 10 50 42 am](https://user-images.githubusercontent.com/42427647/44694511-329ec780-aab1-11e8-97c5-ea032f68db48.png)

I tried to play around with the argument idloc (= 1 or 2) too but the error is still there:
![screen shot 2018-08-28 at 10 51 47 am](https://user-images.githubusercontent.com/42427647/44694525-477b5b00-aab1-11e8-8b9e-23e644c12038.png)
![screen shot 2018-08-28 at 10 52 12 am](https://user-images.githubusercontent.com/42427647/44694528-4c400f00-aab1-11e8-9f71-3cc060f2c714.png)

It seems to me that it can't read the sleeplog file - but I am not sure which part went wrong as I did it as per the documentation.

**Comment by vincentvanhees** [comment]
Possibly something is wrong with the formatting of the csv file, e.g. tab rather than comma separated values. Try to assess how the values are separated, e.g. by opening the file in a text editor like notepad.

To speed up your investigation, you may want to first investigate whether function g.loadlog in GGIR can load your data. This function is responsible for loading the sleeplog file. See the function documentation for further instructions.

**Comment by KHC745** [comment]
Hi Vincent,

Thanks for the suggestion. I have opened the csv file using notepad and the format seems correct i.e. values are separated by comma.
![screen shot 2018-09-05 at 2 26 13 pm](https://user-images.githubusercontent.com/42427647/45071093-f6eea800-b117-11e8-8931-b53564d5721c.png)

However, the same error occurred when I tried to load the sleep log file using the g.loadlog function. 
![screen shot 2018-09-05 at 2 26 37 pm](https://user-images.githubusercontent.com/42427647/45071125-1d144800-b118-11e8-99f6-c5150eb12fa3.png)

I wonder if there could be other errors for that to happen?

**Comment by KHC745** [comment]
Hi Vincent,
Sure. Attached the sample of the sleeplog for your perusal. 

(ps. I can't upload the csv file over here so i saved it as XLSX. You may need to convert the file into CSV format.)
[sleeplog_trial.xlsx](https://github.com/wadpac/GGIR/files/2354824/sleeplog_trial.xlsx)

**Comment by vincentvanhees** [comment]
You do not have a waking up time for the 7th night. The function expects two columns per night, one for going to bed and one for waking up. I understand that you may not have that data, so in that case you should still create the 15th column, but just leave it empty. What matters is that there are 15 columns (14 for the timestamps and 1 for the person identifier).
