### ISSUE TITLE
Help: I am in doubt about an object in L266. 

### ISSUE THREAD

**Issue by iandanilevicz** [wadpac/GGIR#1118]
https://github.com/wadpac/GGIR/blob/4d53aa1c1e959431bb6a99deb7ae3f1cdf883dd2/R/g.part6.R#L266-L277

Hi Vincent, can you provide a simple example of the object fragmode?

**Comment by vincentvanhees** [comment]
It is first "day" and then "spt", which means that the first time we calculate fragmentation metrics for daytime and the second time for spt time. This is what I explained in my email.
