### ISSUE TITLE
Sleep Log: Missing Onset or Offset 

### ISSUE THREAD

**Issue by michelle-kubicki** [wadpac/GGIR#1153]
Hello! General question, we have some sleep log days in which only either a waketime or bedtime is provided, but not both. I've attached a screenshot of the log formatting for these cases. In the full and cleaned outputs we've found some strange results, such as output ignoring the onset/offset label and counting two consecutive waketimes as sleep and wake timing, resulting in what looks like a sleep period of only around 20 minutes. For nights where either sleep onset or offset are missing, should we just keep both onset and offset data blank to let GGIR analyze the night using just actigraphy data instead of the log? Or would we just have to use results found in the QC folder? We'd like to still have these nights included in the report, even if a waketime or bedtime is missing. 

<img width="666" alt="Capture" src="https://github.com/wadpac/GGIR/assets/123568943/87ae2596-12e4-4ced-b699-d3bfcfe0b6d1">

**Comment by vincentvanhees** [comment]
Hello, GGIR ignores the sleeplog for a night if it cannot find both onset and wakeup are available.

Possible solutions you may want to consider:
- Impute the missing sleeplog. For example by inspecting the visualreport produced by GGIR or by taking the mean from other days in the sleeplog.
- Make sure accelerometer-based detection is a reasonable back-up option. It sounds like this is currently not the case, so you would have to tailor your GGIR script to use other parameters or other guiders in line with your study conditions.
