### ISSUE TITLE
Error reading bin file

### ISSUE THREAD

**Issue by jmkurka83** [wadpac/GGIR#120]
Hello,
I've encountered an error that I haven't been able to solve when reading in a bin file a geneactiv device. I'm running GGIR version 1.6-7 using the code copied from the vignette documentation. Below are the traceback results
7: array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), 
       NULL) else NULL)
6: as.matrix.default(isitageneactive)
5: as.matrix(isitageneactive)
4: getbrand(filename, datafile)
3: g.inspectfile(datafile)
2: g.part1(...)
1: g.shell.ggir(...)

And this is the file name: 11021__046152_2018-09-24 23-01-59.bin

**Comment by vincentvanhees** [comment]
You may need to re-install R package GENEAread.
Somehow when GGIR is installed it does not always install all its dependencies. The error message indicates to me that the code has trouble identifying the accelerometer brand. Brand recognition is done by simply trying to read a few seconds of the file.

**Comment by jmkurka83** [comment]
Thank you, Vincent! Seems to be processing now.
