### ISSUE TITLE
 "create_test_acc_csv" does not produce file that is useful for testing

### ISSUE THREAD

**Issue by christmanjc** [wadpac/GGIR#122]
I found source code for create_test_acc_csv outside of package since not available in package. Then when using the csv it creates, it produces error in stage 4 report

Report part 4
 loading all the milestone data from part 4 this can take a few minutes
Error in personSummary[, (cnt + 1):ncol(personSummary)] : 
  subscript out of bounds

**Comment by vincentvanhees** [comment]
As I just responded to your other issue #121 create_test_acc_csv is only supposed to work within the context of the package unit tests. I would advise trying out the package with an example of a real accelerometer recording as I discussed in #121.
