### ISSUE TITLE
Part 4: Error in if (is.na(defaultGuider)) { : argument is of length zero`

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#1225]
Someone reported to me the part 4 error:
`1Error in if (is.na(defaultGuider)) { : argument is of length zero`
based on default GGIR settings.

I investigated it and see it is triggered by night number 0 to exist in the part 3 output, caused by revisions to function `g.det.sib` in the past year which made that night number 0 can be left in the data during the DST hour in the spring, which then is confusing for part 4 where night number is defined as the range in values in night number column of the part 3 output.

I am now working on a fix.

**Comment by jhmigueles** [comment]
Hi, I have just observed the same and I was investigating this as well. Let me know if you need any help or you want me to double-check anything with another dataset. FYI, I observed this in the DST hour change in the autumn (not spring). 

It could be a good opportunity to revise the internal function `dstime_handling_check` within `g.sib.det`, I drafted some code for this in the branch "sleep_horAngle".

**Comment by vincentvanhees** [comment]
I drafted a solution in https://github.com/wadpac/GGIR/tree/issue1225_DST_part3 and am waiting for Mike to confirm that this fixes the issue for him.

Explanation:
