### ISSUE TITLE
Date not recognized in Actigraph csv file using dd.mm.yyyy

### ISSUE THREAD

**Issue by kristin8** [wadpac/GGIR#125]
Hi Vincent,
I´ve seen that this issue was already discussed before but I have another date format like e.g. in #18.
I try to use the shell function (g.shell.GGIR; GGIR version 1.6-7) and get this error:
![grafik](https://user-images.githubusercontent.com/44461787/47486086-d8677c00-d83f-11e8-87ae-c503edd50e77.png)

 
The meta data of my ActiGraph csv are:
![grafik](https://user-images.githubusercontent.com/44461787/47486112-e4533e00-d83f-11e8-9d74-e00100474719.png)

 
Unfortunately, I could not find an option in ActiLife to change the date format.
Do you have an idea how to solve this issue?
Best regards,
Kristin

**Comment by vincentvanhees** [comment]
Hi Kirstin,
What does the first line of the csv say?
See line 107-127 in [this](https://github.com/wadpac/GGIR/blob/5da23885fa48135e349301f68e2fadc87a4dd58b/R/g.getstarttime.R) GGIR function for all the date format variants in Actigraph files that GGIR can handle.
Vincent

**Comment by kristin8** [comment]
Hi Vincent,
Thanks for your fast reply!
The first line of the csv is 

------------ Data   File Created By ActiGraph GT3X+ ActiLife v6.11.9 Firmware v1.7.0 date format   dd.MM.yyyy at 30 Hz  Filter Normal   -----------
--

It is the date format B3 (line 112). Maybe there is another reason for the error than the date format.

**Comment by vincentvanhees** [comment]
Can you copy the first 100 lines of the file into a new csv-file and upload the new csv-file here? I can have a quick look at it.

**Comment by JanDygryn** [comment]
Hi Vincent and Kristin,
We have exactly the same problem with the format of date here in Czech Republic.
Regarding to GGIR function our format is under code B4.

Once I change the format of date manually in "NotePad++" trouble is solved and package is running properly.

Here is my file with first 100 lines

[D121.zip](https://github.com/wadpac/GGIR/files/2548346/D121.zip)

Thanks a lot for your help. I have 700 files and I hope there will be another options then rewrite a format manually in each of them.

Jan,
Czech Republic

**Comment by vincentvanhees** [comment]
The date, month and year in your data are separated by dots rather than - or / as in 20.05.2016 rather than 20-05-2016.
I have now fixed this here on GitHub and that should avoid the need for manually editing the date format. We will include this fix in the next CRAN release of GGIR. Thanks for reporting the issue.
