### ISSUE TITLE
re-opening issue #119 sleep efficiency

### ISSUE THREAD

**Issue by albacabre** [wadpac/GGIR#131]
Thanks for your feedback, I have been checking the data since then and still cannot see why if for subject 1 we have recorded 8 nights at the end we are only getting sleep efficiency for two nights. I have checked what you suggested but I think these night we loose do not have much invalid data.

In this [shared ](https://drive.google.com/drive/folders/1mR2vOg2o7700es_u45h_Fmnq2458dNnw?usp=sharing)folder there is an excel file with an example using one participant (part2, part4, and part5 are all summarized in one excel sheet). Can you see why part5 only gives us information for two night?

Many thanks!

_Originally posted by @albacabre in https://github.com/wadpac/GGIR/issues/119#issuecomment-437417475_

**Comment by vincentvanhees** [comment]
see #139
