### ISSUE TITLE
Invalid date format when importing sleep data

### ISSUE THREAD

**Issue by jcapde** [wadpac/GGIR#135]
This issue was identified by  @akramhussein 

In `part4_nightsummary_sleep_full.csv.txt`  there is invalid data for the field `sleeplog_onset_ts`. Should be a timestamp in the format %H:%M:%S however in some rows it is a decimal e.g. 0.958333333.

``` 
doubleDigitClocktime = function(x) {
              x = unlist(strsplit(x,":"))
              xHR = as.numeric(x[1])
              xMI = as.numeric(x[2])
              xSE = as.numeric(x[3])
              if (xHR < 9) xHR = paste("0",xHR,sep="")
              if (xMI < 9) xMI = paste("0",xMI,sep="")
              if (xSE < 9) xSE = paste("0",xSE,sep="")
              x = paste(xHR,":",xMI,":",xSE,sep="") 
              return(x)
}
```
Code above is clearly wrong and should be `< 10` to cover `09`

**Comment by vincentvanhees** [comment]
Thanks @akramhussein and @jcapde!
I have now merged pull-request  #137, so I close this issue.
