### ISSUE TITLE
Problem importing Actigraph CSV. file

### ISSUE THREAD

**Issue by Anjolu** [wadpac/GGIR#138]
Hi,

I got some problem when importing my Actigraph CSV. file to R studio to run the GGIR. I keep getting the error message which is: "Error in if (sf == 0) sf = 80 : missing value where TRUE/FALSE needed".  I attached a sample of my csv. file in the zip file. Looking forwards to having some suggestion here. 

Thanks very much!
Anjo

[TMCI_041 (2018-04-19)60sec.csv.zip](https://github.com/wadpac/GGIR/files/2598796/TMCI_041.2018-04-19.60sec.csv.zip)

**Comment by vincentvanhees** [comment]
The file seems to hold epoch level data generated by ActiLife. GGIR is designed to process raw data. You will need to export the raw Actigraph data to a csv file with ActiLife before you can use GGIR.
