### ISSUE TITLE
error generating report part4

### ISSUE THREAD

**Issue by albacabre** [wadpac/GGIR#139]
I got this problem, any clue of where this issue might come from?

![image](https://user-images.githubusercontent.com/35957191/48898499-355d4e80-ee4d-11e8-906b-502ce5d0ead2.png)

**Comment by vincentvanhees** [comment]
Alba - I have helped you several times in the past and every time encouraged you to consider my [support service](https://www.movementdata.nl/how-to-help-sustain-ggir). From now I will only help you if you have paid for my time. You can find all the information to sign up in the blog post.
