### ISSUE TITLE
Support for files from camntech actiwatch

### ISSUE THREAD

**Issue by acamargofb** [wadpac/GGIR#141]
Hi GGIR community:

Does someone has an idea how to use the GGIR package with data comming from Camntech actiwatch?

Any help will be useful,

Thanks a lot in advance,

Aldo

**Comment by vincentvanhees** [comment]
Hi Aldo,
The camntech data format is currently not supported by GGIR. However, I am happy for this to be added.
So,the question is more: Who is willing to do this or wants to pay for the work? See also my recent [response](https://groups.google.com/d/msg/RpackageGGIR/CpJfjm3xa2M/n6VWdleXBwAJ) to a message from a Shimmer co-worker regarding facilitating their data format.
Best regards, 
Vincent
