### ISSUE TITLE
Make outputdir path more robust

### ISSUE THREAD

**Issue by JianWang2016** [wadpac/GGIR#15]
When the phrase "output" is contained in outputdir path, go.part1 couldn't store results in proper location.

**Comment by rx96304** [comment]
I keep getting the following error while g.cwaread'ing a 2-week cwa file
Error code 1: data in block too short for doing non-wear detection
What's the bench mark for "too short' data?
Thanks.

**Comment by vincentvanhees** [comment]
@rx96304 your comment to unrelated to issue #15, please post as separate issue. I am not going to answer unrelated questions in a thread related to the outputdir path.
