### ISSUE TITLE
Separate different "Error"

### ISSUE THREAD

**Issue by JianWang2016** [wadpac/GGIR#16]
Dear Vincent,
While running a 14 day .cwa file, there are a few error codes in the Part 1.  It appears relevant to the following description:
"Next, the moving average over the nonmovement periods is taken from each of the three orthogonal sensor axes and used to generate a three-dimensional ellipsoid representation that should ideally be a sphere with radius 1 g. Here, deviations between the radius of the three-dimensional ellipsoid and 1 g (ideal calibration) can then be used to derive correction factors for sensor axis-specific calibration error."

Prio to autocalibration
Error (g) before:
[1] 0.04281636

Post autocalibration
Error (g) after:
[1] 0.003218808

In this context, "Error is somehow expected" - not a bad thing.  But "Error" can be misunderstood as failure of program.  

Another example of "Error" is 
Error code 1: data in block too short for doing non-wear detection, it seems also not a bad error code.  I guess this block of data is not big enough to be processed.

Then I have a really scary "Error" in Part 5.  It failed right there.  

I would like to propose to output different levels of Error.  Or the 2nd place, instead of "Error", using "Warning"?  

Part 5
 1
Error in if (time_num < 12) time_num = time_num + 24 : 
  missing value where TRUE/FALSE needed

=====================

Part 1
[1] "P1 file1"
[1] "---------------------------------------------"
[1] "investigate calibration of the sensors..."
[1] "Loading block: 1"
[1] "Loading block: 2"
[1] "Loading block: 3"
[1] "Loading block: 4"
[1] "Loading block: 5"

End of file reached

stop reading because there is not enough data in this block

----------------------------------------
Summary of autocalibration procedure:

Status:
[1] "recalibration attempted with all available data, but possibly not good enough: Check calibration error variable to varify this"

Error (g) before:
[1] 0.04281636

Error (g) after:
[1] 0.003218808

Offset correction:
[1] -0.005223742  0.072656300  0.065878741

Scale correction:
[1] 1.0062811 0.9864897 1.0310247

Number of hours used:
[1] 48

Number of 10 second windows around the sphere:
[1] 8236

Temperature used (if available):
[1] TRUE

Temperature offset (if temperature is available):
[1] -4.225358e-05  2.101107e-03 -2.662689e-03

----------------------------------------
[1] "get meta data..."

warning: g.cwaread in beta version

Loading block: 1
Loading block: 2
Loading block: 3
Loading block: 4
Loading block: 5
Loading block: 6
Loading block: 7
Loading block: 8
Loading block: 9
Loading block: 10
Loading block: 11
Loading block: 12
Loading block: 13
Loading block: 14
Loading block: 15
Error code 1: data in block too short for doing non-wear detection
[1] "save .RData-file with: calibration report, file inspection report and all meta data..."

___________________________________

**Comment by vincentvanhees** [comment]
thanks, the frist two occurances related to calibration error, so these are not software errors but measurement errors. I will add the word Calibration in the next release to avoid confusion

Most of the other 'errors' can indeed by replaced by 'Warning', except from the one generated by part5 which truly relates to an error.
