### ISSUE TITLE
Using Philips Respironics

### ISSUE THREAD

**Issue by araikes** [wadpac/GGIR#161]
I'm looking forward toward doing some sleep actigraphy analyses using GGIR (hopefully). I've read the documentation, the Google Groups, and the Github issue log and haven't found the answer to my question yet.

Are Philips Respironics Actigraphs supported? The Philips software (Actiware) produces timestamped CSVs. I can't provide an example at this second (doing this at home right now) but I could provide a de-identified example on Monday if needed.

Thanks for any help you can be.

**Comment by vincentvanhees** [comment]
Your description [here](https://groups.google.com/d/msg/rpackageggir/xWRmHfGhw-Q/4Lp7hSlCDAAJ) indicates that you are not working with raw data, by which GGIR will not be applicable.
