### ISSUE TITLE
starttime0 issue 

### ISSUE THREAD

**Issue by kc142909** [wadpac/GGIR#163]
Hello,

This issue is similar to #54 and #75, wherein I get the 'starttime0 not found' error when loading ActiGraph csv files. I believe this is another date format problem as my date is in the m/dd/yy format, but when I change it to m/dd/yyyy it works and previous files using m/dd/yyyy work as well. I have updated R and all my packages, etc. 
Is there a way to tell GGIR to accept start dates in m/dd/yy format or a way for me to manually define the start date instead of having GGIR pull it from the header?

Thank you for your time!

**Comment by vincentvanhees** [comment]
GGIR facilitates 16 timestamp formats (see function [g.getstarttime](https://github.com/wadpac/GGIR/blob/master/R/g.getstarttime.R) lines 112-130).
Would it be possible for you to change your system- or ActiLife timestamp format settings to one of those 16 timestamp formats before you generate the csv files?

If you want me to update GGIR then some [financial support](https://www.movementdata.nl/how-to-help-sustain-ggir) would be appreciated. Another option of course is that you fix it yourself and make a pull request.

Thanks, Vincent
