### ISSUE TITLE
ws=3 is hardcoded in g.plot5.r

### ISSUE THREAD

**Issue by TavoloPerUno** [wadpac/GGIR#197]
Hello! 

g.shell.GGIR calls with custom short epoch size (ws3) via windowsizes parameter, with visual report generation set to true for part 5, results in different x-y lengths for plots error if the study includes days when transitions in/ out of DST happen. This is due to this codeblock (lines 298 - 303) of g.plot5.R, where the main metric aggregated to short epoch intervals is divided by 12 * 60 to get the number of hours.

`if (((t1-t0) + 1) / (12*60) == 25) { # day with 25 hours, just pretend that 25th hour did not happen
            t1 = t1 - (12*60)
          }
          if (((t1-t0) + 1) / (12*60) == 23) { # day with 23 hours, just extend timeline with 1 hour
            t1 = t1 + (12*60)
          }
`

**Comment by vincentvanhees** [comment]
Thanks!
