### ISSUE TITLE
Using GGIR for data logged via a mobile phone

### ISSUE THREAD

**Issue by loneharoon** [wadpac/GGIR#209]
Hi,

Can we use GGIR for the data logged via a mobile phone?  This [vignette](https://cran.r-project.org/web/packages/GGIR/vignettes/GGIR.html#other-resources) does not mention anything about mobile phone data.

**Comment by vincentvanhees** [comment]
Hi, GGIR is designed to be applied to data files. If your phone can produce a data file that matches one of the accepted data formats and contains three acceleration signals for at least half a day in duration day then it should be possible. I am working on facilitating a broad range of csv formats in the branch [issue185_readCsvGeneric](https://github.com/wadpac/GGIR/tree/issue185_readCsvGeneric), which may be relevant if you want to explore this.
