### ISSUE TITLE
Set clipping and non-wear thresholds outside of for loops

### ISSUE THREAD

**Issue by m-patterson-wearable** [wadpac/GGIR#215]
The clipping and non-wear thresholds are being set inside two for loops in the g.getmeta.R function. By moving these sections before the for loops, it will decrease the number of times the code has to run those lines and speed up code efficiency. These thresholds are not being adjusted within these loops, so it is OK to set them up higher in the code. The first for loop iterates over every ws2 window in the data chunk being analyzed and the second loop iterates over x, y and z accel channels on each ws2 chunk.

**Comment by vincentvanhees** [comment]
thanks for doing this in pull request #218
