### ISSUE TITLE
part5.R time_num at line 656

### ISSUE THREAD

**Issue by JianWang2016** [wadpac/GGIR#22]
Vincent:
    An error encountered with Part 5.  It is the line at 656-658 of part5.R.   This seems to be introduced in the release 1.5.9.  Any insight where could cause this?  Your advice is greatly appreciated.
(I have no sleep diary, 15 days of data, used the sample script from https://cran.r-project.org/web/packages/GGIR/vignettes/GGIR.html with minor changes)

Part 2
 1
________________________________________________________________________________________________________________________________________________________________
Part 3
 1
________________________________________________________________________________________________________________________________________________________________
Part 4
 1
________________________________________________________________________________________________________________________________________________________________
Part 5
 1
Error in if (time_num < 12) time_num = time_num + 24 : 
  missing value where TRUE/FALSE needed
> 

================
g.shell.GGIR(#=======================================
             mode=mode,
             datadir=datadir,
             outputdir=outputdir,
             f0=f0, f1=f1,
             
             
             
             #-------------------------------
             # Part 1:
             #-------------------------------
             # Key functions: reading file, auto-calibration, and extracting features
             do.enmo = TRUE,             do.anglez=TRUE,
             chunksize=1,                printsummary=TRUE,
             #-------------------------------
             # Part 2:
             #-------------------------------
             strategy = 2,               ndayswindow=14,
             hrs.del.start = 0,          hrs.del.end = 0,
             maxdur = 15,                 includedaycrit = 16,
             winhr = c(5,10),
             qlevels = c(c(1380/1440),c(1410/1440)),
             qwindow=c(0,24),
             ilevels = c(seq(0,400,by=50),8000),
             mvpathreshold =c(100,120),
             bout.metric = 4,
             closedbout=FALSE,
             #-------------------------------
             # Part 3:
             #-------------------------------
             # Key functions: Sleep detection
             timethreshold= c(5),        anglethreshold=5,
             ignorenonwear = TRUE,
             #-------------------------------
             # Part 4:
             #-------------------------------
             # Key functions: Integrating sleep log (if available) with sleep detection
             # storing day and person specific summaries of sleep
             excludefirstlast = FALSE,
             includenightcrit = 6,
             def.noc.sleep = c(),
             #loglocation= "C:/mydata/sleeplog.csv",
             outliers.only = TRUE,
             criterror = 4,
             relyonsleeplog = FALSE,
             sleeplogidnum = TRUE,
             colid=1,
             coln1=2,
             do.visual = TRUE,
             nnights = 14,
             #-------------------------------
             # Part 5:
             # Key functions: Merging physical activity with sleep analyses
             #-------------------------------
             threshold.lig = c(30), threshold.mod = c(100),  threshold.vig = c(400),
             boutcriter = 0.8,      boutcriter.in = 0.9,     boutcriter.lig = 0.8,
             boutcriter.mvpa = 0.8, boutdur.in = c(1,10,30), boutdur.lig = c(1,10),
             boutdur.mvpa = c(1),   timewindow = c("WW"),
             #-----------------------------------
             # Report generation
             #-------------------------------
             # Key functions: Generating reports based on meta-data
             do.report=c(2,4,5),
             visualreport=TRUE,     dofirstpage = TRUE,
             viewingwindow=1)

**Comment by JianWang2016** [comment]
Dear all,  Just want to follow up on this issue.  It continues in the release of 1.5.17.  Any insight is greatly appreciated.

**Comment by vincentvanhees** [comment]
I may have fixed this now, and will include this in the next release version of GGIR on CRAN in the upcoming days. Let me know if the problem persists.
