### ISSUE TITLE
Bout criterion part.5 VPA and MPA

### ISSUE THREAD

**Issue by WassenaarT** [wadpac/GGIR#220]
Hi Vincent,

Currently, it is possible to set a certain bout criterion for MVPA/Lig/In (part 5). I was wondering whether it is also possible to set this threshold  separately for VPA and MPA? 

Thanks,
Thomas

**Comment by vincentvanhees** [comment]
Thanks for the suggestion Thomas. Somehow I completely missed or forgot about your issue.... or did I respond via a different route??? Either way, separate VPA and MPA bouts are not possible at the moment. I suppose this could be an addition. I am a bit busy at the moment to work on it, but if someone wants to develop this or if someone wants to pay me to do this later in the year then that get in touch.

**Comment by vincentvanhees** [comment]
Closing this issue. If you want MPA and VPA bouts use a vigorous threshold for the MVPA bout option, and a light threshold for the moderate bouts. It is unclear to me whether being able to detect bouts in inactivity, light, moderate, and vigorous in a single analysis is important. Either way it would take a lot of work. Either someone else will have to do the work and make a pull request or hire me to do the work.
