### ISSUE TITLE
timezone is hard coded in part5.R

### ISSUE THREAD

**Issue by JianWang2016** [wadpac/GGIR#23]
Vincent, 

I noticed desiredtz sometimed hard coded in part5.R               

               L5HOUR = as.character(iso8601chartime2POSIX(L5HOUR,tz="Europe/London"))
               M5HOUR = as.character(iso8601chartime2POSIX(M5HOUR,tz="Europe/London"))

Thanks for your attention.

**Comment by vincentvanhees** [comment]
thanks, this has now been fixed.
