### ISSUE TITLE
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection

### ISSUE THREAD

**Issue by adsalmon** [wadpac/GGIR#297]
Hi all, 

I am trying to knit some code from a class I am taking, and have loaded the .Rdata package, however when I try to run that line, I keep getting 

Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection

Can someone help me? Thank you!

**Comment by vincentvanhees** [comment]
- provide reproducible example
- clarify context: class? knit? data? ... and what did you try to do... version of R? version of GGIR?
- explain what you have done to solve the problem.

Feel free to re-open the issue after you have provided these things.
