### ISSUE TITLE
Code quality and speed

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#3]
Code quality and speed need to be improved. Some functions are too large, variable names are often too cryptic and there is still some repetition of code that could be moved into generic functions.

**Comment by Mirkes** [comment]
In g.cwaread function there are repetition of big fragment. It is result of decision to use this scheme because of 
1. call function in R is not fast enough
2. I cannot modify array "on place" in subfunction
3. Call function with big array in arguments is very slow.
