### ISSUE TITLE
Typo in a g.getmeta warning message 

### ISSUE THREAD

**Issue by MikeOMa** [wadpac/GGIR#304]
if ((ws2/60) != round(ws2/60)) {
    ws2 = as.numeric(60 * round(ws2/60))
    cat("\nWARNING: The long windowsize needs to be a multitude of five minutes periods. The\n")
    cat(paste("\nlong windowsize has now been automatically adjusted to: ",ws2," seconds in order to meet this criteria.\n",sep=""))
  }

Really new to this package. Noticed it was telling me that  windowsize needs to be a multitude of 5 minutes period. But I think it means 1 minute period?

**Comment by vincentvanhees** [comment]
Thanks for spotting this! I am going to fix it.
