### ISSUE TITLE
Cleaning git history rubbish

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#309]
Hi @jhmigueles, @m-patterson and anyone else planning to make future pull requests.

The git history of GGIR includes some large files from the past. They were deleted a long time ago, but still live in the git history. This makes that the GGIR repository size on your machine is 50 MB instead of 10MB. It also causes the GitHub contributor [overview](https://github.com/wadpac/GGIR/graphs/contributors) to think that I contributed 500000 lines of code, while in reality it is somewhere around 87000. I have now deleted the large files, which addresses these issue for now. 

However, as soon as one of you makes a pull request from your own fork all those old large files that still lives in your forks will be re-inserted, and we are back where we started.

To address this there are two options:

### 1. Remove the unwanted files from your fork's git history with the following git commands:

First git checkout your own fork and make sure that your local and remote version of that fork are in sync. Next:
```
git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch GGIR_1.*' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch "old releases/GGIR*"' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch input_cls/tud_data.csv' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch pdf_vignettes_for_github_only/*' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch GGIR.Rcheck/*' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch GGIRExeter.Rcheck/*' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin

git reflog expire --expire=now --all
git gc --prune=now
git gc --prune=now

git push origin --force --all
git push origin --force --tags
```

### 2. Stop using the `git merge` command when you want to move the latest changes in the wadpac/GGIR repo to your fork and use `git rebase` instead.

This would be the solution if you cannot or do not want to run the commands above.

On a different note - If you want to see which large files are left in the git history use the following command:

```
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- \
| $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest \
| awk '$2 >= 2^20'
```

**Comment by m-patterson** [comment]
Thanks for that info Vincent, it solved the issue on my end
