### ISSUE TITLE
Running GGIR without sleeplog

### ISSUE THREAD

**Issue by jcpsantiago** [wadpac/GGIR#31]
I have some example GENEactive .bin and pre-processed csv files, but no sleep log. The shell script says GGIR will integrate sleep log (if available), but I can't find a way to run my code without an error in part 4:
`Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input`
Because there is no file.

Am I missing something?

**Comment by vincentvanhees** [comment]
The pre-processed csv files from the GENEActiv software are not suitable input for GGIR. Please make sure you only process the .bin files with GGIR.
If that does not address your issue then please post your exact function call here and some more information about what you are trying to do. Thanks
