### ISSUE TITLE
Reading a csv-file results in date-duplication in two languages

### ISSUE THREAD

**Issue by Weyaaron** [wadpac/GGIR#316]
I'm runnnig version GGIR 1.11-0 on Arch Linux and R-Version 4.0.2 , with data from
Actilive-Devices and the following custom parameters:

```
library(GGIR)
g.shell.GGIR(
  mode = c(1, 2, 3, 4, 5),
  datadir = "./testin",
  outputdir = "./testout",
  do.report = c(2, 4, 5),
  timewindow = c("MM"),
  visualreport = FALSE)
warnings()
```
Since my goal was to simplify investigation, I removed most of 
the actual parameters, let me know if you need them.

When running on a particular file, the output of the Day-Summary-File
includes the following lines:

> [...]
> [...],"MOS2A05140424 (2020-02-14)RAW.csv.RData","Thursday","2020-02-20"
> [...],"MOS2A05140424 (2020-02-14)RAW.csv.RData","Donnerstag","2020-02-20"

These two lines are suspicious output, for two reasons:
The date is duplicated, and the language has changed. 

R issues about 40 of these warnings:
```
Warning in if (length(spocum) > 0 & class(spocum) == "matrix" & length(calendardate) >=  :
  the condition has length > 1 and only the first element will be used
```

This is one my my first issues on github, if you need additional data or the  formating  of this post is off let me know.

**Comment by vincentvanhees** [comment]
Can you retry with the latest GGIR version on CRAN and/or here on GitHub?
I think I fixed this issue before the 2.0 release. Thanks
