### ISSUE TITLE
Bug converting to time from daysleeper option in HDCZA sleep detection

### ISSUE THREAD

**Issue by m-patterson** [wadpac/GGIR#324]
I have a test in which the HDCZA algorithm detects sleep close to noon, so the algorithm reprocess the sleep period using data from 6pm to 6pm (instead of noon to noon). However, when the code translates these sleep/wake detection points, it does not take into account that the times were starting from 6pm instead of 12-noon. 

After the detection (HDCZA) algorithm is run, the code goes into this section to translate the sample number from the chunk sent into HDCZA into times:
![image](https://user-images.githubusercontent.com/16383946/88567712-da0e3700-d005-11ea-8049-2a543a731a0c.png)

There is no option for starting at 6pm instead of 12-noon. 

I will add this in a new feature branch and make a pull request.

**Comment by m-patterson** [comment]
Before the fix, this test resulted in ~2pm sleeponset time and ~3am wake time:
![image](https://user-images.githubusercontent.com/16383946/88574058-b2bc6780-d00f-11ea-8577-9be9bf04a299.png)

However, upon inspection it did go into the daysleeper aspect of HDCZA detection and returned samples 1 and 10275:
![image](https://user-images.githubusercontent.com/16383946/88574302-1f376680-d010-11ea-909c-cc30e420c15f.png)

This corresponds to hrs 12 and 2.2, which make sense considering they will then be used as 'guiders' to get the final sleeponset and wakeup times. How can we have a sleeponset guider starting at 12-noon, when the chunk of data started at 6pm? The code is not taking into account the adjusted start time.

With this fix in the code (add daysleep_offset) to the code:
![image](https://user-images.githubusercontent.com/16383946/88575201-7a1d8d80-d011-11ea-86d5-49897c37f51e.png)

We still have 1 and 10275 as the detection points from the HDCZA:
![image](https://user-images.githubusercontent.com/16383946/88575239-902b4e00-d011-11ea-908c-f804e9eec415.png)

However, the resulting times are correct, considering the 6pm start of the block:
![image](https://user-images.githubusercontent.com/16383946/88575304-afc27680-d011-11ea-902e-1cf1c89ffcf4.png)

I also cleaned up the legacy code in there.

**Comment by vincentvanhees** [comment]
thanks, now merged into master
