### ISSUE TITLE
Error in writing date to part5_daysummary_MM

### ISSUE THREAD

**Issue by m-patterson** [wadpac/GGIR#346]
I have encountered a bug in writing dates to the part5_daysummary_MM... csv file.

Here, it can be seen that first day is repeated twice with different information:
![image](https://user-images.githubusercontent.com/16383946/92631311-2c967080-f29f-11ea-8b73-116e5af7d942.png)

However, upon viewing the part5_daysummary_WW... csv file, it can be seen that the same data is written, but the first date is now correct (Tues instead of Wed):
![image](https://user-images.githubusercontent.com/16383946/92631408-4fc12000-f29f-11ea-9e80-87ff988ea0ec.png)

Also, from part4_nightsummary... csv it can be seen that Tues night has the same sleep / wake times as the first line in part5_daysummary_MM:
![image](https://user-images.githubusercontent.com/16383946/92631611-96167f00-f29f-11ea-9e7f-ca4b69aabe50.png)

@vincentvanhees I'll have a go at fixing this, but if you have a chance to have a look at it, let me know and I'll send the data to you.

**Comment by vincentvanhees** [comment]
I can have a look later today or tomorrow. These are things I worked on earlier this year, so I think it is a part of the code I still have fresh in memory. @m-patterson If you could send me the example files that would be great. Thanks
