### ISSUE TITLE
set dayborder to other value than 0

### ISSUE THREAD

**Issue by RubenBrondeel** [wadpac/GGIR#400]
Trying to set the dayborder setting to 3 (g.shell.ggir or g.part3), the following error was trown back:
Error in { : task 1 failed - "missing value where TRUE/FALSE needed"

The problem originates from the function 'checkmidnight'. hours, minutes, seconds are added to 1 value to find the value corresponding with the dayborder. For 0, this is fine. But for eg 3, several times can be added to the result 3 (e.g. 00:03:00, or 02:01:00), not just 03:00:00.

I suggest to change this code to the following, or something similar:

checkmidnight = function(x) {
  temp1 = matrix(unlist(strsplit(x, ":")), ncol = 3, byrow=T)
  temp1[which(temp1[,2] != '00' | temp1[,3] != '00'),1:3] = NA
  return(as.numeric(temp1[,1]))
}

The bug has repercussions on 'g.detecmidnight' in 'g.sib.det' in 'g.part3'
The error then occurs in 'g.sib.plot'

Greetings, 
Ruben.

**Comment by vincentvanhees** [comment]
Thank you @RubenBrondeel! Good catch.
I have now prepared a slightly more compact solution, where I convert "HH:MM:SS" first to hour in the day with decimal places: "02:01:00" will become 2.01667, and "03:00:00" will become 3.
