### ISSUE TITLE
time handling in sleeponset when dayborder is not 0

### ISSUE THREAD

**Issue by RubenBrondeel** [wadpac/GGIR#404]
'Sleeponset' (and 'wakeup') seem to be off by the number of hourse used in dayborder. This is apparent in for example, the ms4.out and the file summary reports. 

The issue seems to originate from sptwindow_HDCZA() in g.sib.det(), where indexes are used to calculate time. I think that adding the dayborder value (times the observations per hour)  could be a solution.
Contact me if you would like some output to clarify the issue.

**Comment by vincentvanhees** [comment]
thank you @RubenBrondeel for spotting all these issues.
It has been busy week for me with other things, but I will try to have a look at them in the upcoming week.
I will let you know if anything is unclear.
