### ISSUE TITLE
create_test_acc_csv() errors out for some Nmin values

### ISSUE THREAD

**Issue by l-k-** [wadpac/GGIR#411]
`create_test_acc_csv()` is failing whenever `Nmin` is such that one of the sleep blocks starts just before the end of the recording but doesn't end within the recording. Same issue for non-wear periods and activity periods.

For instance, `create_test_acc_csv(Nmin = 3000)` is attempting to create a non-wear block that runs past the end of the recording, resulting in an error:

> GGIR::create_test_acc_csv(Nmin = 3000)
Error in [<-(*tmp*, nw3, 1, value = accx) : subscript out of bounds

And this example creates a too-long last activity block:

> GGIR::create_test_acc_csv(Nmin = 2311)
Error in testdata[, 1] <- testdata[, 1] + ACC :  number of items to replace is not a multiple of replacement length

And this ends up with an error because of a too-long last sleep block:

> GGIR::create_test_acc_csv(Nmin = 2309)
Error in `[<-`(`*tmp*`, sleep_periods, 1, value = accx + round(rnorm(n = length(sleep_periods),  :  subscript out of bounds

The problem is that while `create_test_acc_csv()` *is* making sure that sleep/non-wear/activity blocks *start* within the recording period, it isn't making sure that these blocks also *end* within the recording period.

I sent in a pull request: https://github.com/wadpac/GGIR/pull/410

In there, I modified `create_test_acc_csv.R` to test various `Nmin` values that lead to errors.

I also provided a fix for the issue; I think it works. The fix ensures that no sleep block (or non-wear block, or activity block) ends after the end of the recording. If a block is too long to fully fit within a recording, it gets truncated.

**Comment by vincentvanhees** [comment]
Thank you, nice solution! I have now merged the pull request and will close this issue.
