### ISSUE TITLE
GGIR variables per hour (error)

### ISSUE THREAD

**Issue by FitBrainLab** [wadpac/GGIR#429]
### Hi all, 

First of all thanks for this amazing package. It makes my research with raw accelerometry data so much easier!!

I've been running codes for a while now, and succesfully use the following code for my data (AX3 accelerometer, 14 days of data 50Hz, 8g).
`g.shell.GGIR(mode=c(1,2,3,4,5),datadir="C:/Users/Participants wearable data/5_0043/5_0043_T0/5_0043_T0_data", outputdir="C:/Users/Participants wearable data/5_0043/5_0043_T0/5_0043_T0_results", do.report=c(2,4,5), strategy = 1, hrs.del.start = 0,hrs.del.end = 0, maxdur = 16, overwrite = TRUE, includedaycrit = 16, qwindow=c(0,24), mvpathreshold =c(100), bout.metric = 4, excludefirstlast = FALSE, includenightcrit = 16,def.noc.sleep = 1,nnights = 16,outliers.only = FALSE, criterror = 4,do.visual = TRUE, threshold.lig = c(30),threshold.mod = c(100),threshold.vig = c(400),boutcriter = 0.8,boutcriter.in = 0.9,boutcriter.lig = 0.8, boutcriter.mvpa = 0.8, boutdur.in = c(1,10,30), boutdur.lig = c(1,10),boutdur.mvpa = c(1), timewindow = c("WW"), visualreport=TRUE, print.filename=TRUE, IVIS_windowsize_minutes=60, IVIS_epochsize_seconds=30)`

However, this gives me average data and I would really like to get the data per hour. Vincent van Hees was so nice to advice me to change the command qwindow=c(0,24) to qwindow=c(0:24). I use the exact same code, yet change the , to :.

Leaving me with this code:
`g.shell.GGIR(mode=c(1,2,3,4,5),datadir="C:/Users/Participants wearable data/5_0043/5_0043_T0/5_0043_T0_data", outputdir="C:/Users/Participants wearable data/5_0043/5_0043_T0/5_0043_T0_results", do.report=c(2,4,5), strategy = 1, hrs.del.start = 0,hrs.del.end = 0, maxdur = 16, overwrite = TRUE, includedaycrit = 16, qwindow=c(0:24), mvpathreshold =c(100), bout.metric = 4, excludefirstlast = FALSE, includenightcrit = 16,def.noc.sleep = 1,nnights = 16,outliers.only = FALSE, criterror = 4,do.visual = TRUE, threshold.lig = c(30),threshold.mod = c(100),threshold.vig = c(400),boutcriter = 0.8,boutcriter.in = 0.9,boutcriter.lig = 0.8, boutcriter.mvpa = 0.8, boutdur.in = c(1,10,30), boutdur.lig = c(1,10),boutdur.mvpa = c(1), timewindow = c("WW"), visualreport=TRUE, print.filename=TRUE, IVIS_windowsize_minutes=60, IVIS_epochsize_seconds=30)`

However, when running the code I get the following errors (starting at part 2):

##GGIR version:  2.3-0

   Do not forget to cite GGIR in your publications via a version number and
   Migueles et al. 2019 JMPB. doi: 10.1123/jmpb.2018-0063. 
   See also: https://cran.r-project.org/package=GGIR/vignettes/GGIR.html#citing-ggir 

__________________________________________________________________________________________________________________________________________________________________________
Part 1

Checking that user has read access permission for all files in data directory: Yes
Checking that user has write access permission for directory specified by argument outputdir: Yes

 Busy processing ... see C:/Users/Participants wearable data/5_0043/5_0043_T0/5_0043_T0_results/output_5_0043_T0_data/meta/basic for progress

__________________________________________________________________________________________________________________________________________________________________________
Part 2

 Busy processing ... see C:/Users/Participants wearable data/5_0043/5_0043_T0/5_0043_T0_results/output_5_0043_T0_data/ms2 for progress

Errors and warnings for meta_55871_0000000000.cwa.RData$message
[1] "subscript out of bounds"

$call
`[<-`(`*tmp*`, di, collectfi, value = "")

__________________________________________________________________________________________________________________________________________________________________________
Part 3

 Busy processing ... see C:/Users/Participants wearable data/5_0043/5_0043_T0/5_0043_T0_results/output_5_0043_T0_data/ms3 for progress

Errors and warnings for NA$message
[1] "cannot open the connection"

$call
readChar(con, 5L, useBytes = TRUE)

Errors and warnings for NA$message
[1] "cannot open the connection"

$call
readChar(con, 5L, useBytes = TRUE)

__________________________________________________________________________________________________________________________________________________________________________
Part 4
 1Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'C:/Users//Participants wearable data/5_0043/5_0043_T0/5_0043_T0_results/output_5_0043_T0_data/meta/ms3.out/NA', probable reason 'No such file or directory'

Am I overseeing something, or is it not possible to do the hour values with such a big dataset? Hopefully I'm just missing some important issue. 
I already tried to cut the data in half (by hrs.del.end=168). But this does not seem to solve the problem unfortunatly.

Many thanks in advance for looking at this issue!

**Comment by vincentvanhees** [comment]
If I understand correctly we have talked about this before. Please refer to the original conversation such that context and chat history is clear. Using an anonymous GitHub account without adding your name to your post is not helpful.

It appears like the issue is with GGIR part 2, so I would turn off part 3 and 4 for the moment and first focus on getting a report for part 2.

The 1 hour resolution should work. Did you try an intermediate resolution, e.g. qwindow = c(0, 13, 24)? Possibly that helps to understand whether it is just the 1 hour resolution or something else. Also, it would be good to understand whether the issue is specific to a single file or happens with all your data.
