### ISSUE TITLE
g.getmeta does not read movisens files

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#438]
**Describe the bug**
g.getmeta fails at reading movisens files, yet g.calibrate reads them well. I suspect the issue is in lines 255-262 of g.getmeta. First the object "accread" is removed, and few lines after it is required:
      **rm(accread)**; gc()
      options(warn=0) # to ignore warnings relating to failed mmap.load attempt
      if(mon == 5) { # if movisens, then read temperature
        PreviousStartPage = **accread$startpage**
        temperature = g.readtemp_movisens(datafile, desiredtz, PreviousStartPage, PreviousEndPage)
        P = cbind(P, temperature[1:nrow(P)])
        colnames(P)[4] = "temp"
      }

**To Reproduce**
1. Sensor brand: Movisens bin files
2. Data format: binary
3. Approximate recording duration 7 days (but it shouldn't matter)
4. Are you using a sleep diary to guide the sleep detection: NO
5. Copy of R command used: 
g.shell.GGIR(mode = c(1:5),          #Parts of GGIR to run
             #BASIC SETTINGS
             datadir = 'D:/accelerometry/storage/Rostock/',   
             outputdir = "D:/accelerometry/processing/Rostock/", 
             studyname = "Rostock",             
             f0 = 1, f1 = 10000,
             overwrite = T, 
             print.filename = T, printsummary=T,
             #G.PART1: GET ENMO VALUES
             windowsizes = c(5,900,3600),     #First number is the epoch length
             desiredtz = "Europe/Stockholm",  
             do.enmo = T, do.anglez = T,  #Metrics to calculate
             dayborder = 0,                  
             #G.PART2: FIRST ESTIMATIONS OF PHYSICAL ACTIVITY 
             idloc = 2, 
             strategy = 1,
             hrs.del.start = 0, hrs.del.end = 0,
             maxdur = 0,
             includedaycrit = 16,    
             winhr = c(5,10),
             qwindow = c(0,24), 
             qlevels = c(960/1440,              #M1/3 (8h)
                         1320/1440, 1380/1440,  #M120, M60
                         1410/1440, 1430/1440,  #M30, M10
                         1435/1440, 1438/1440), #M5, M2
             ilevels = seq(0,800, by = 50),
             mvpathreshold = 100,
             boutcriter = 0.8, bout.metric = 4, 
             #G.PART3-4: SLEEP CLASSIFICATION
             anglethreshold = 5,timethreshold = 5,
             # loglocation = c(),
             loglocation = "D:/accelerometry/processing/MINISTOP/loglocation/GGIR_log_FUp_final_johanna.csv",
             colid = 1, coln1 = 2, nnights = 10,
             sleeplogidnum = FALSE,
             do.visual = TRUE, 
             outliers.only = FALSE,
             includenightcrit = 0,
             #G.PART5: MERGE SLEEP AND PHYSICAL ACTIVITY DATA (DEFINITIVE DATASET)
             threshold.lig = 35, threshold.mod = 100, threshold.vig = 400,        
             boutdur.mvpa = c(1,5,10), boutdur.in = c(10,20,30), boutdur.lig = c(1,5,10), 
             boutcriter.mvpa = 0.8, boutcriter.in = 0.9, boutcriter.lig = 0.8, 
             timewindow = c("MM", "WW"),
             save_ms5rawlevels = TRUE, save_ms5raw_without_invalid = FALSE,
             save_ms5raw_format = "RData",
             data_cleaning_file=c(),
             week_weekend_aggregate.part5 = TRUE,
             #REPORTS
             do.report = c(2,4,5),
             visualreport = T, 
             do.parallel = F)
6. Have you tried processing your data based on GGIR's default argument values? Does the issue you report still appear? YES

**Before submitting**
- [X ] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ X] Have you tried this on the latest `master` branch from GitHub?

**Comment by vincentvanhees** [comment]
thanks, now merged
