### ISSUE TITLE
do.part3.pdf argument

### ISSUE THREAD

**Issue by TheTS** [wadpac/GGIR#449]
The *do.part3.pdf* argument that is part of part3 never changes from the default value (TRUE) if specified in g.shell.GGIR.

I needed to turn off the PDF as I was getting an error with files that have no valid days (might be another bug for a separate issue).

```
g.shell.GGIR(
  mode = 1:3,
  datadir=datadir,
  outputdir=outputdir,
  do.part3.pdf = FALSE # This does not work
)
```

Probably need to add the argument to the g.part3 call in g.shell.GGIR.r on L424

```
g.part3(metadatadir=metadatadir,f0=f0, acc.metric = acc.metric,
  f1=f1,anglethreshold=anglethreshold,timethreshold=timethreshold,
  ignorenonwear=ignorenonwear,overwrite=overwrite,desiredtz=desiredtz,
  constrain2range=constrain2range, do.parallel = do.parallel,
  myfun=myfun, maxNcores=maxNcores, do.part3.pdf = do.part3.pdf          # Add here
)
```

**Comment by vincentvanhees** [comment]
Thanks Tom, I am going to fix this in upcoming week.
