### ISSUE TITLE
g.part1 run on fnames instead of fnamesfull when datadir is a list of full paths

### ISSUE THREAD

**Issue by ft-zhang** [wadpac/GGIR#495]
**Describe the bug**
When supplying a list of full filepaths as the datadir argument to g.shell.GGIR, g.part1 and main_part1 within it are run using the fnames only and not the full paths. Thus, input files are not found (as they are not located in my home directory)/ file(fname, 'rb') throws 'cannot open the connection' errors.

**To Reproduce**
Running g.shell.GGIR with datadir as a list of full filepaths to .cwa files

1. Sensor brand: Axivity AX3 and AX6
2. Data format: .cwa binary
3. Approximate recording duration 14 days
4. Are you using a sleep diary to guide the sleep detection: No
5. Copy of R command used: 

datadir <- '/home/actigraphy/subjects/'
data.list <-dir(datadir, recursive = TRUE, pattern = "[.]cwa", full.names = TRUE)
g.shell.GGIR(

  mode=c(1,2,3,4,5),
  datadir=data.list,
  studyname='test_1',
  outputdir="/home/actigraphy/ggir/",
  do.report=c(1,2,3,4,5),
  do.parallel=FALSE
)

6. Have you tried processing your data based on GGIR's default argument values? Does the issue you report still appear? Yes

**Expected behavior**
g.part1 to run using perhaps fnamesfull instead of fnames so g.cwaread can find them

**Screenshots**
If applicable, add screenshots to help explain your problem. Note that usually we are not only interested in see the error message in red, but all GGIR output to the console.
![Screenshot_2022-01-21_14-46-01](https://user-images.githubusercontent.com/15311362/150590784-1607e0f7-a086-4f91-9451-20dee320ff83.png)

**Desktop (please complete the following information):**
 - OS: linux-gnu x86_64
 - GGIR Version 2.5-6

**Before submitting**
- [ X ] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ X ] Have you tried this on the latest `master` branch from GitHub?

**Comment by vincentvanhees** [comment]
Thanks for reporting and sorry about this.
I have now made a direct commit to the master branch that should fix this.
