### ISSUE TITLE
g.part4 attempts to add newlines when spo is NULL

### ISSUE THREAD

**Issue by ft-zhang** [wadpac/GGIR#496]
**Describe the bug**
g.part4 attempts to run the sleep-cleaning block with cleaningcode = 5 when spo is NULL. This causes an error when the newlines matrix instantiated with NULL rows is assigned new rows on line 541. This may be because the condition on line 535 to trigger this block, length(which(spo[, 2] < SptWake & spo[, 3] > SptOnset)) == 0 , returns TRUE when spo is NULL. spo may be NULL as line 517 re-defines spo as the rbind of spo_dayk and spo_day2k (k in this instance may be T5A5), when both spo_dayk and spo_day2k are NULL.

**To Reproduce**
Running g.shell.GGIR with default parameters.

1. Sensor brand: Axivity AX3 and AX6
2. Data format: .cwa binary
3. Approximate recording duration 14 days
4. Are you using a sleep diary to guide the sleep detection: No
5. Copy of R command used:

datadir <- '/home/actigraphy/subjects/'
data.list <-dir(datadir, recursive = TRUE, pattern = "[.]cwa", full.names = TRUE)
g.shell.GGIR(

mode=c(1,2,3,4,5),
datadir=data.list,
studyname='test_1',
outputdir="/home/actigraphy/ggir/",
do.report=c(1,2,3,4,5),
do.parallel=FALSE
)
6. Have you tried processing your data based on GGIR's default argument values? Does the issue you report still appear? Yes

**Expected behavior**
g.shell.GGIR to run without error

**Screenshots**
If applicable, add screenshots to help explain your problem. Note that usually we are not only interested in see the error message in red, but all GGIR output to the console.
![Screenshot_2022-01-23_10-21-17](https://user-images.githubusercontent.com/15311362/150685618-4e8a8abc-9d70-4119-a3ce-09db5e494556.png)

**Desktop (please complete the following information):**
 - OS: linux-gnu x86_64
 - GGIR Version 2.5-6

**Before submitting**
- [ X ] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ X ] Have you tried this on the latest `master` branch from GitHub?

**Comment by vincentvanhees** [comment]
Thanks for reporting. Are you able to share with me (v.vanhees@accelting.com) the milestone data file (.RData) stored by GGIR in the output folder meta/basic? Having a test file would be helpful for me to work on this.
