### ISSUE TITLE
g.part4 spo is character instead of numeric matrix

### ISSUE THREAD

**Issue by ft-zhang** [wadpac/GGIR#499]
**Describe the bug**
In g.part4, spocum and spo become character matrices at some point before line 591 in g.part4. When line 591 is run, an attempt is made to subtract 24 from a character of a float (i.e. "41.29012") thus returning a non-numeric argument to binary operator error. This may be because spo contains a character column specifying k (i.e. "T5A5"), making the entire matrix character.

**To Reproduce**
Running g.shell.GGIR with default params

1. Sensor brand: Axivity AX3 and AX6
2. Data format: .cwa binary
3. Approximate recording duration 14 days
4. Are you using a sleep diary to guide the sleep detection: No
5. Copy of R command used:

datadir <- '/home/actigraphy/subjects/'
data.list <-dir(datadir, recursive = TRUE, pattern = "[.]cwa", full.names = TRUE)
g.shell.GGIR(

mode=c(1,2,3,4,5),
datadir=data.list,
studyname='test_1',
outputdir="/home/actigraphy/ggir/",
do.report=c(1,2,3,4,5),
do.parallel=FALSE
)

6. Have you tried processing your data based on GGIR's default argument values? Does the issue you report still appear? Yes

**Expected behavior**
g.part4 to run without error

**Screenshots**
![Screenshot_2022-01-24_12-05-59](https://user-images.githubusercontent.com/15311362/150830132-4de429bb-f798-4d2c-bb59-5383206cea6a.png)

**Desktop (please complete the following information):**
 - OS: linux-gnu x86_64
 - GGIR Version 2.5-6

**Before submitting**
- [ X ] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ X ] Have you tried this on the latest `master` branch from GitHub?

**Comment by vincentvanhees** [comment]
Thanks for reporting @ft-zhang This code not recent code, so it surprises me that I have not spotted this before.
I have now tidied it up by changing the spo, spocum and spocum.t matrices into a data.frame structure that can hold multiple variable classes.

Would you mind checking that this resolves your issue? To install do:
remotes::install_github("wadpac/GGIR", ref = "issue499_move_spo_to_df")
