### ISSUE TITLE
#538 introduces bug when processing single file

### ISSUE THREAD

**Issue by tarensanders** [wadpac/GGIR#558]
**Describe the bug**
See these posts on the google group ([one](https://groups.google.com/g/rpackageggir/c/s6rZArvWxaM), [two](https://groups.google.com/g/rpackageggir/c/Qfgp3Sc71lg)).

The error `Error in makePSOCKcluster(names = spec, ...) :  numeric 'names' must be >= 1` is because of the revision in #538, where if you are processing a single file you are trying to create a cluster of size 1.

https://github.com/wadpac/GGIR/blob/ad8b919d6cee56209884a2b537fb0b5795eb3679/R/g.part2.R#L208-L211

`(f1 - f0) +1` = 1

To resolve, don't use parallel processing if Ncores2use == 1.

```r
if (length(params_general[["maxNcores"]]) == 0) params_general[["maxNcores"]] = Ncores
Ncores2use = min(c(Ncores - 1, params_general[["maxNcores"]], (f1 - f0) + 1))
if (Ncores2use > 1){
    cl <- parallel::makeCluster(Ncores2use) #not to overload your computer
    doParallel::registerDoParallel(cl)
    } else {
        params_general[["do.parallel"]] = FALSE
    }
```

I can make this change if you want.

**Comment by vincentvanhees** [comment]
Good idea, if you could make a PR then yes please.
I am aiming to upload a new GGIR release to CRAN at the end of next week. So, if you could do it before then that would be great.
