### ISSUE TITLE
ActiLife csv 

### ISSUE THREAD

**Issue by asridhar1** [wadpac/GGIR#56]
Hi Vincent, 

I am trying to use ActiLife to export data to use in GGIR. I've exported it without the timestamp but I'm still having difficulties getting GGIR to run. I am getting the error: 
Error in data.frame(value = H[, 2], row.names = H[, 1]) : 
  duplicate row.names: 0

Would you be able to provide a sample csv that works with GGIR? Or inform me what measures can be analyzed with GGIR. I've provided a screenshot of the possible measures that can be included. 

Thank you,
Anissa 
![screen shot 2017-12-05 at 2 25 08 pm](https://user-images.githubusercontent.com/20704760/33626771-8fefbbb0-d9c9-11e7-80a7-17d852d89b11.png)

**Comment by Alex-Row** [comment]
Hi Anissa,

It looks as if you are converting the ActiGraph epoch agd files to csv files. To use the files in GGIR you need the raw csv files. 

You can get these by selecting 'Raw to Raw' from the 'Import/Export/Convert' menu in Actilife and converting the raw gt3x files to raw csv files. See attached screenshot.

Best,
Alex
