### ISSUE TITLE
GGIR only supports one type of file path on Windows

### ISSUE THREAD

**Issue by tarensanders** [wadpac/GGIR#570]
**Describe the bug**
I'm just running a couple of files to test #567 and noticed an issue with file paths. 

On Windows, both `C:/Users/user/folder` and `C:\\Users\\user\\folder` are valid file paths. While the former is definitely clearer, the latter is easier if you need to copy a long folder path into R (you can copy from file explorer and use `readClipboard()` to get an escaped filepath). The problem is that some parts of GGIR assume that folders are always separated by `/`, and this causes issues. E.g., https://github.com/wadpac/GGIR/blob/536ffafee772440638fd14aee70b3f493441a65c/R/GGIR.R#L74-L75

**To Reproduce**
Here's an example of the problem, using that line above as an example:

``` r
# This works as expected
datadir <- "C:/Users/taren/Desktop/gene_files"
outputdir <- "C:/Users/taren/Desktop/outdir"
outputfoldername = unlist(strsplit(datadir, "/"))[length(unlist(strsplit(datadir, "/")))]
metadatadir = paste0(outputdir, "/output_", outputfoldername)
outputfoldername
#> [1] "gene_files"
metadatadir
#> [1] "C:/Users/taren/Desktop/outdir/output_gene_files"
# But could also just be replaced by:
basename(datadir)
#> [1] "gene_files"
file.path(outputdir, "output_", basename(datadir))
#> [1] "C:/Users/taren/Desktop/outdir/output_/gene_files"

# This file path is valid, but fails in GGIR
datadir <- "C:\\Users\\taren\\Desktop\\gene_files"
outputdir <- "C:\\Users\\taren\\Desktop\\gene_files"
outputfoldername = unlist(strsplit(datadir, "/"))[length(unlist(strsplit(datadir, "/")))]
metadatadir = paste0(outputdir, "/output_", outputfoldername)
outputfoldername
#> [1] "C:\\Users\\taren\\Desktop\\gene_files"
# metadatadir is not a valid file path
metadatadir
#> [1] "C:\\Users\\taren\\Desktop\\gene_files/output_C:\\Users\\taren\\Desktop\\gene_files"
# The builtin can already handle this format.
basename(datadir)
#> [1] "gene_files"
# And can make a valid file path
file.path(outputdir, "output_", basename(datadir))
#> [1] "C:\\Users\\taren\\Desktop\\gene_files/output_/gene_files"
```

<sup>Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

You might not want to fix this, but maybe it should be noted in the vignette? 

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch from GitHub?

**Comment by vincentvanhees** [comment]
Thanks Taren and sorry for the slow reply. I am now in the process of facilitating this.
User will be able to use `\\` and GGIR internally converts this to `/` in order not to upset all downstream code that assumes `/`.
