### ISSUE TITLE
Log whether idle.sleep.mode was encountered in ActiGraph data

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#571]
Enhance ActiGraph idle.sleep.mode handling with automated logging of whether timegaps where found.
I am guessing ActiGraph idle.sleep.mode is not stored as part of the data.

**Comment by rouzbeh** [comment]
Idle sleep mode actually is stored in GT3x files. We have updated the documentation (see the table here: https://github.com/actigraph/GT3X-File-Format, type EVENT). 

The python library is now also capable of catching these events.

**Comment by vincentvanhees** [comment]
Thanks @rouzbeh
Ok, I think that is then best dealt with in the R package read.gt3x which interacts with the .gt3x file, while GGIR uses read.gt3x.

Also, as of the upcoming release, GGIR will automatically detect and handle idle sleep mode based on gaps between timestamps. So, this issue has become less urgent.

One minor outstanding action point is to record in the GGIR output if timegaps were encountered.
