### ISSUE TITLE
Part 4 report summary collapses files with the same IDs

### ISSUE THREAD

**Issue by tarensanders** [wadpac/GGIR#583]
**Describe the bug**
I'm not certain this is a bug or intended, but it's not documented.

I'm reprocessing files from a large project which has three time points. The output in the reports for parts 2 & 5 ("part`x`_summary") have a row for each file that is processed (i.e., the filename is the ID for the row). But, the output for the part 4 report assumes that the ID is unique, and so you only get one row per ID (even if there are multiple files for this ID).

**To Reproduce**
You could do this with dummy data, but here an example from my data. I have three files for one participant, each ~12m apart:

0112__019874_2017-06-13  13-47-36.bin
0112__019596_2018-06-19  13-30-30.bin
0112__031435_2019-07-17  14-33-53.bin

When I process these, I get three rows in the `part2_summary` output, and three rows in the `part5_personsummary...` output. It's useful to know that the `meas_dur_def_proto_day` reported in part 2 is 4/8/8.

In part4_summary_sleep_cleaned, there's only one row for this participant ("0112__019596_2018-06-19 13-30-30.bin") and 15 nights of sleep (i.e., more than is just in this file).

I'm not sure if this is the intended behaviour. That is, maybe the intention is that some users will have multiple devices for the same participant, and want an overall summary? But, if that's the case it should be consistent across all three reports.

1. Sensor brand: Geneactiv
2. Data format: raw (`.bin`)
3. Approximate recording duration 8 days
4. Are you using a sleep diary to guide the sleep detection: NO
5. Copy of R command used: (N/A, you can repo with the default command in the vignette)
6. Have you tried processing your data based on GGIR's default argument values? Does the issue you report still appear? YES

**Expected behavior**
Expected filename to be the unique ID in all cases.

**Screenshots**
Part 2
![Screen Shot 2022-06-22 at 11 13 18 am](https://user-images.githubusercontent.com/20055916/174922540-b9f6cfa3-b576-448f-b024-5d47d742175d.png)
Part 4
![Screen Shot 2022-06-22 at 11 13 26 am](https://user-images.githubusercontent.com/20055916/174922539-b54bf175-021d-4194-a605-a0e03ce2bdca.png)
Part 5
![Screen Shot 2022-06-22 at 11 13 37 am](https://user-images.githubusercontent.com/20055916/174922526-a85132ea-5b77-48f8-933b-e910e801c5da.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - GGIR Version: Master brach

**Additional context**
If you agree this is not the intended behaviour, I'm happy to try and resolve. Or, if it is the intended behaviour I can add to the docs.

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch from GitHub?

**Comment by vincentvanhees** [comment]
Thanks Taren for your detailed report on this. Yes, I think this is a bug. I suspect the problem is that days are aggregated per per person based on person ID, which works if there are no repeated measures of the same individual. To accommodate for repeated measures we should use accelerometer filename instead as that is typically unique for each recording. I am out of office this week (work visit abroad) and will catch-up with this and other GGIR issues in the upcoming weeks.
