### ISSUE TITLE
Movisens file info

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#588]
At the moment GGIR does not attempt to extract the ID or serial number from the movisens data. Unclear whether R package unisensR facilitates this at the moment. The XML file in the Movisens data indicates that ID and serial number are stored, so it would be good if we could try to extract this.

**Comment by vincentvanhees** [comment]
This is not an ideal solution, but at least a way to enable ID extract for the time being. Next steps:

- [ ] Interact with unisensR package about getting this implemented on their side
- [ ] Test with various Movisens sensors.

**Comment by jhmigueles** [comment]
I have now posted an issue in the [unisensR](https://github.com/Unisens/unisensR/issues/7) repository.
