### ISSUE TITLE
Issue with result from Part3

### ISSUE THREAD

**Issue by jmkurka83** [wadpac/GGIR#597]
Hi Vincent! Sorry for the delay in following up. I'm using GGIR 2.7-1 and unfortunately I don't have a different machine I can use to test. It does have 32 GB of RAM though. 
I have 2 files that I'm having trouble with. I'll focus on the first here. It looks like parts 1 and 2 finish with no errors or warnings. However, there is no dataset in ms2.out. There are no files in the 'results' folder, not even in the QC folder.
Part 3 shows the error along with warnings. I've attached a copy of the console if that is helpful.

[21072 console.txt](https://github.com/wadpac/GGIR/files/8946572/21072.console.txt)

_Originally posted by @jmkurka83 in https://github.com/wadpac/GGIR/issues/556#issuecomment-1161345133_

**Comment by jmkurka83** [comment]
Hi Vincent. Wondering when you might have a chance to help with this issue. Thank you!

**Comment by vincentvanhees** [comment]
I replied here: https://github.com/wadpac/GGIR/issues/556#issuecomment-1161345133
