### ISSUE TITLE
error when runing g.shell.GGIR with "mode=c(1), visualreport = TRUE, ..."

### ISSUE THREAD

**Issue by yaojiali** [wadpac/GGIR#60]
Hi Vincent,

I was running GGIR on csv files from Actigraph, and I ran with g.shell.GGIR(). I first filled in all the arguments for g.shell.GGIR function that intends for mode = c(1, 2, 3, 4, 5). to make sure that each part in run after the previous one has finished, I change the mode = c(1) when I ran it in HPC cluster. Yet I kept getting message of error after message ""Warning: First run g.shell.GGIR with mode = 4 to generate required milestone data". Then I looked at the source code for function g.shell.GGIR(), I found that the function doesn't seem to allow for "mode=c(1), visualreport = TRUE, ...", this could be caused by the codes between line 240 and 247.

![g shell ggir](https://user-images.githubusercontent.com/16377746/34326732-0afb42f0-e8ef-11e7-9e00-f9b93c94d93d.PNG)

if possible, could you kindly have a look at it~~
Thanks a lot!

Regards,
Jiali

**Comment by vincentvanhees** [comment]
Hi Jiali,
This is because you are probably using do.report=c(4) in your call of g.shell.GGIR, which then complains that mode =4 was not done yet. If you turn this of or replace it by do.report = c(), it should fix your problem.
Best, Vincent

**Comment by yaojiali** [comment]
Thank you very much Vincent!
