### ISSUE TITLE
Error at beginning of run: 1 Error in if (dformat == 1 & is.mv == FALSE) { :    argument is of length zero

### ISSUE THREAD

**Issue by leightjt** [wadpac/GGIR#607]
Hi,

I've just started using GGIR. I've started with an axivity ax3 .cwa file
I input:
GGIR(datadir="cwa_files",outputdir="results")

and I get the following error:
1 Error in if (dformat == 1 & is.mv == FALSE) { : 
  argument is of length zero

Any advice would be much appreciated.
Thanks,
Leigh

**Comment by leightjt** [comment]
So I think I may have solved this issue. 
For any incompetent new users like me in the future, make sure .cwa is in lower case in the file name...

Thanks,
Leigh

**Comment by vincentvanhees** [comment]
Interesting, how did it end up being in uppercase? OMGUI has always exported the files with lowercase extension I believe, but it would be good to know if there is route where files are exported in uppercase. If yes, then we could modify GGIR to also consider uppercase .CWA a valid extension for Axivity files.

**Comment by vincentvanhees** [comment]
@leightjt please let me know your thoughts?

**Comment by Ranudar** [comment]
Dear Vincent
I've just downloaded about 200 raw data files from the ActigraphCorph CentrePoint website, and all files have a ".CSV" file ending...

**Comment by vincentvanhees** [comment]
For Axivity cwa/CWA format this was fixed in PR https://github.com/wadpac/GGIR/pull/744 

> I've just downloaded about 200 raw data files from the ActigraphCorph CentrePoint website, and all files have a ".CSV" file ending...

This issue does not related to ActiGraph. Please create a new issue and try to answer the questions I asked here: https://github.com/wadpac/GGIR/issues/737 If you do not know the answers then please contact the ActiGraph people first.

**Comment by Ranudar** [comment]
Dear Vincent

I've given more information here:

https://groups.google.com/g/RpackageGGIR/c/AOOnKdA3FkM?pli=1

If you think I should open an issue on github, I'll of course do so.

Thanks a lot for your effort and help!
Christian
