### ISSUE TITLE
Move long time gaps imputation to epoch level

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#622]
When the time gaps to be imputed are very long, they make that the R session crashes. 

**Solution:** identify time gaps longer than 90 minute, skip them in g.imputeTimegaps, and impute them in the epoch level phase of the analysis.

**Comment by vincentvanhees** [comment]
same as https://github.com/wadpac/GGIR/issues/522?

**Comment by vincentvanhees** [comment]
Re-opening this issue: We did most of the work, but alignment may not be perfect after undoing the breaking changes via #368.
