### ISSUE TITLE
AX6 data fails to be handled by g.getmeta

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#623]
In g.getmeta, when processing axivity AX6 files, it is supposed to ignore the gyroscope data. However, the gyroscope data fails to removed, which bring problems later on when extracting the acceleration metrics.

**Comment by vincentvanhees** [comment]
Thanks. Looks like the main issue is that `gyro_available` is set to TRUE, which is no logical because we are actually removing the columns. Your PR seems to fix that.

I am now testing this and will merge the PR when tests pass.
