### ISSUE TITLE
Remove .cff and zenodo files

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#636]
Remove the [.cff](https://github.com/wadpac/GGIR/blob/master/CITATION.cff) and [zenodo](https://github.com/wadpac/GGIR/blob/master/.zenodo.json) files from the GGIR repository for the following reasons:

1. It will ease tracking GGIR citations. At the moment it is unclear how we can see who has cited the zenodo doi for GGIR. Citations of journal publications describing GGIR on the other hand are clearly indexed on Google scholar and this is how I have been able to keep track of GGIR usage. In contrast, I am not able to find citations for the GGIR zenodo doi via Google scholar.
2. It is unclear whether journals always list zenodo doi citations in their official journal references. As a result, such citations may not be captured by websites like Google scholar.
3. It simplifies citing GGIR by just one citation to a journal article (Migueles et al. 2019) and by mentioning a GGIR version number that was used. The citation of GGIR-release-specific doi numbers feels odd, because R packages are already indexed by unique version number (CRAN makes sure of that). Having a new doi for every release will only add more complexity and introduce the risk for human mistakes in copying all those numbers and references.
4. GGIR and all its past versions are [archived](https://cran.r-project.org/src/contrib/Archive/GGIR/) by CRAN (and on GitHub). Having an additional archive on Zenodo seems redundant and introduces ambiguity about what software to cite and use.
5. It makes that GGIR is no longer tracked by the [RSD](https://www.research-software.nl/), by which GGIR will go down in their ranking of recently updated software tools. This is good, because it will clarify to RSD visitors that the RSD profile for GGIR is not actively maintained. As a side effect the google ranking for the profile will hopefully go down, by which GGIR users in need for support are more likely to find my own website and less likely to end up on the RSD website.
6. Reduction in the number of root files in this repository.

Tagging @jspaaks as a heads up that I am planning to deprecate the .cff and zenodo functionality for GGIR.

**Comment by jspaaks** [comment]
Hi Vincent, thanks for the heads up, I don't think it will break anything --famous last words, I know. As to SEO aspects of the GGIR site on the Research Software Directory, there are probably things we can do. Might be worth filing an [issue for the new RSD](https://github.com/research-software-directory/RSD-as-a-service/issues) (we're in the process of phasing out the version that you are familiar with. Not sure when exactly, maybe this year? @jmaassen knows more.)
