### ISSUE TITLE
Part 5 Error 

### ISSUE THREAD

**Issue by kl91** [wadpac/GGIR#68]
I am using GENEActiv and I tried to run the g.shell.GGIR on the raw .bin files and got this error:

![ggir error](https://user-images.githubusercontent.com/34115642/36087395-21f2b86a-0fca-11e8-80c0-bfbd5ffb2ff9.JPG)

Many Thanks,
Khai

**Comment by vincentvanhees** [comment]
Thanks, this is only a warning and I am aware of it. It is related to how the data is handled, this needs to be tidied up, but does not affect calculations. Vincent
