### ISSUE TITLE
unit of measurement WE_[0,50)_mg_15.01-24h_ENMO

### ISSUE THREAD

**Issue by kl91** [wadpac/GGIR#69]
Dear all, 

Just requesting a bit of help in determining the units for the data from the variable labelled WE_[0,50)_mg_15.01-24h_ENMO

To my understanding, the unit measurement is in minutes. Could anyone clarify if my interpretation of 539.33 under this column represents 539.33mins spent in 0 - 50mg (which is sedentary)? 

kind regards, 
Khai

**Comment by vincentvanhees** [comment]
Yes, I can confirm, You may notice that these minutes add up to 1440 minutes per 24 hours.
