### ISSUE TITLE
Part 2: Error in matrix(0, nwindow_f, 1)

### ISSUE THREAD

**Issue by DiegoGBassani** [wadpac/GGIR#7]
Hi Vincent - Thanks for the most recent update. I am now running it again and getting a new type of error when it reaches part2:

Error in matrix(0, nwindow_f, 1) : invalid 'nrow' value (< 0)

I have now set all metrics to == TRUE so I do not run into the same problem as before, but still getting this nrow error.

Thanks

Diego

**Comment by vincentvanhees** [comment]
Hi Diego, I meant to write = TRUE, not == TRUE, in our [google group discussion](https://groups.google.com/d/topic/rpackageggir/RY8wzp7_Dos/discussion). If that does not fix it, please do some research first: Start with the default settings - which is the same as not entering any function arguments - and then itereratively adding your desired input argument. Thanks

**Comment by DiegoGBassani** [comment]
Thanks - and yes, I am using =TRUE - that is not the issue. Let ,me try as you suggested and see how it goes.
D

On May 10, 2017, at 3:30 PM, Vincent van Hees <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Diego, I meant to write = TRUE, not == TRUE, in our google group discussion<https://urldefense.proofpoint.com/v2/url?u=https-3A__groups.google.com_d_topic_rpackageggir_RY8wzp7-5FDos_discussion&d=DQMFaQ&c=Dvjge31PR3JZstzk2paJYiflTxRSxp35GBhsbHdd2Zw&r=600aQL-wbvYHCwho_-DHtESI2DVnFZwRI6SIznFH9mM&m=le4Ay1C_FsbGNDQrROXc1_4JUn6MDwNjoI9HY8nvGCU&s=Edc3NwBgjeg--RUB6voB_iBSbBiKsaUXvD-rdi0RoMo&e=>. If that does not fix it, please do some research first: Start with the default settings - which is the same as not entering any function arguments - and then itereratively adding your desired input argument. Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wadpac_GGIR_issues_7-23issuecomment-2D300588524&d=DQMFaQ&c=Dvjge31PR3JZstzk2paJYiflTxRSxp35GBhsbHdd2Zw&r=600aQL-wbvYHCwho_-DHtESI2DVnFZwRI6SIznFH9mM&m=le4Ay1C_FsbGNDQrROXc1_4JUn6MDwNjoI9HY8nvGCU&s=RGocuwQAqR4qppk1DImoq4ze5k9htEVhce5tWKUgRk4&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbSBksiAyxU96AO4AVeXAZK3L-5FsNa66fks5r4hBVgaJpZM4NXGU3&d=DQMFaQ&c=Dvjge31PR3JZstzk2paJYiflTxRSxp35GBhsbHdd2Zw&r=600aQL-wbvYHCwho_-DHtESI2DVnFZwRI6SIznFH9mM&m=le4Ay1C_FsbGNDQrROXc1_4JUn6MDwNjoI9HY8nvGCU&s=ubCRPCKOfex2bcEt9ref8yANtuHhKTfM0Ch6-p5EJmo&e=>.


________________________________

This e-mail may contain confidential, personal and/or health information(information which may be subject to legal restrictions on use, retention and/or disclosure) for the sole use of the intended recipient. Any review or distribution by anyone other than the person for whom it was originally intended is strictly prohibited. If you have received this e-mail in error, please contact the sender and delete all copies.
