### ISSUE TITLE
Angle formulas in documentation are not correct

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#701]
@jhmigueles the angle formulas in the documentation are not correct as they do not have the square signs as in the [code](https://github.com/wadpac/GGIR/blob/master/R/g.applymetrics.R).
Would you mind fixing this?

**Comment by jhmigueles** [comment]
Sure, let me know when you are ready to merge any of the PRs I did and I will include this minor change in any of them.
