### ISSUE TITLE
problems with checking packageVersion when running GGIR from GitHub

### ISSUE THREAD

**Issue by m-patterson-wearable** [wadpac/GGIR#704]
**Describe the bug**
Not sure if this is just something silly on my end, but when I run GGIR from GitHub (not library) I get errors in 
GGIR.R, createConfigFile.R and g.analyse.perfile.R because of this line:
`as.character(utils::packageVersion("GGIR"))`

Because I don't have GGIR installed as an R-package, I get an error: 'there is no package called 'GGIR' '

Should these lines be dealt with like line 206 in g.part2.R where the GGIR installation is checked first?
`# check whether we are indevelopment mode:
    GGIRinstalled = is.element('GGIR', installed.packages()[,1])`

Maybe I am just missing something obvious, but if you do want this updated let me know and I can push the changes. Thanks.

**Comment by vincentvanhees** [comment]
Hi Math, yes you are correct. Those parts of the code assume that GGIR has been installed and this probably only an issue developers run into. I agree that what you propose could be a nice work around. Do you have time to make a PR for this?
