### ISSUE TITLE
g.loadlog() only accepting "," as column separator

### ISSUE THREAD

**Issue by lvanwel** [wadpac/GGIR#72]
Dear Vincent,

Using g.part4() with a sleeplog CSV-file resulted in the following error:
Error in `[.data.frame`(S, , coln1 + ((i - 1) * 2)) : 
  undefined columns selected

Upon further inspection I found that g.loadlog is called() to read the sleeplog CSV-file, using read.csv(). That function requires the CSV file to use "," as column separator, while my data had ";" as separator. Changing my file to use "," as separator solved the error.

Would it be possible to  either add an argument to g.part4() to specify the separator, or  add a note to the g.part4 documentation that the separator has to be a comma,

**Comment by vincentvanhees** [comment]
Thanks, considering that there are many other issues that need attention I prefer not work on this for now. "csv" stands for comma separated value, so I think it is a reasonable default. Best. Vincent
