### ISSUE TITLE
Clarify better meaning of MXLX and MX

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#723]
Originally GGIR referred to MX and LX as the most and least consecutive X hours in line with literature about M10 and L5.

However, since the MX work by Alex Rowlands and colleagues there is also a different definition of MX, which refers to the most active X non-consecutive hours of the day.

Having both types of MX in GGIR could be confusing and it may be good to check this distinction is correctly made in documentation (and training materials). It may be even necessary to replace them with longer acronym.

**Comment by jhmigueles** [comment]
In the GGIR documentation, the only references I can find to MX, LX are to the most and least consecutive X hours. MX as defined by Alex Rowlands are only referred to as percentiles (qlevels) in GGIR. Is it better to keep it as it is? Or should the MX metrics by Rowlands also be referred to in the GGIR documentation (I mean, with this specific acronym)?

**Comment by vincentvanhees** [comment]
Yes, I think it is good to add a few sentences to explain that the qlevels argument can be used to derive the acceleration values corresponding to the percentiles needed for the MX-metrics by Ben and Alex. I have now asked Ben to help us with this.
