### ISSUE TITLE
Problems with sleep log

### ISSUE THREAD

**Issue by Lhurter** [wadpac/GGIR#73]
Hi Vincent, 

I'm trying to run parts 1-5, with a sleep log. However, I keep getting the error message: 

Error in file(file, "rt") : cannot open the connection In addition: Warning message: In file(file, "rt") : cannot open file 'E:/STUDY_2/sleeplog1to8': No such file or directory

I made a sleep log as described in the instructions (.csv) and specified the loglocation correctly. Can you think of a reason why it can't open my log? Do you perhaps have an example of a sleep log, that I can use (by just adding my own sleep and wake times)? 

Thanks, 
Liezel

**Comment by Lhurter** [comment]
No worries, I figured out what the problem was!

**Comment by Schmay00** [comment]
Hi Liezel

I'm currently running into the same issue. Would you mind sharing your solution?

Thanks
Maya
