### ISSUE TITLE
Accelerometry file size too big

### ISSUE THREAD

**Issue by Varleen99** [wadpac/GGIR#738]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Varleen99** [comment]
I am doing a research on the impact of shift work on food choices, physical activity and sleep in adults.  I am trying to analyze raw data files from GENEActive Accelerometry from Activinsights, each data file is between 700-750 mb, I am not able to analyze it in the R using GGIR package. Do you have any idea about this? Any kind of help will be really appreciated. 
P.S. I am total newbie to R.

**Comment by vincentvanhees** [comment]
Your post is not specific and you ignored the issue template. You cannot expect us to reply to this.

If you want to be trained in using GGIR then you may want to consider signing up for our training courses on R and GGIR: https://www.accelting.com/ggir-training/
