### ISSUE TITLE
Documentation main vignette - trainings

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#746]
[In section 1.2](https://cran.r-project.org/web/packages/GGIR/vignettes/GGIR.html#:~:text=GGIR%20training%20We,accelting.com.) in the main vignette there is information about the GGIR training options. This needs to be updated to the new options available and maybe the duration of the courses can be skipped in the vignette.

**Comment by vincentvanhees** [comment]
I am working on the vignette now and will make a PR soon. This will then remove all references to the specific courses with a general references to the GGIR training website. In that way we do not need to worry about keeping it up to date.
