### ISSUE TITLE
Ideas for future GGIR functionalities

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#758]
This is a list of functionalities that may be useful for some users, but require funding and/or time to develop.

1. Split up recording, e.g. before and after an intervention.
2. ~~Merge recording, e.g. Movisens, Empatica, Verisens and others tend to store data split per day.~~ => work in progress #792
3. Improved management of milestone data: reduce storage redundancy, efficient loading of data in memory, checksums to verify consistency, more platform independent, ....
4. ~~Tools to aid combining accelerometer data with other data such as GPS, GIS, physiological signals.~~ => already in progress via [Habitus-eu](https://github.com/habitus-eu/)

We welcome additional suggestions, and of course support with doing the work and/or finding funding.

**Comment by jhmigueles** [comment]
6. Add calculation of bouts for moderate intensity and vigorous intensity separately (only bouts of MVPA are provided at the moment, from [google group message](https://groups.google.com/g/RpackageGGIR/c/syTMFS-SVkg)).

**Comment by vincentvanhees** [comment]
I am closing this issue as it is not of much practical value. If anyone wants this work to be done they should reach out and organise funding.
