### ISSUE TITLE
Verbose argument needs to be applied within g.getmeta

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#766]
Even if `verbose = FALSE`, g.getmeta would print "Loading chunk 1..." when `do.parallel = FALSE`. This might occur also in other functions, it would be good to double check that.

**Comment by vincentvanhees** [comment]
Note: This is being address as part of https://github.com/wadpac/GGIR/pull/646.
Please remember to tag issues in both commit messages and PRs as that would help track progress on open issue.

**Comment by vincentvanhees** [comment]
Closing because PR has been merged.
