### ISSUE TITLE
sep argument for reading and storing files

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#770]
GGIR users with different default settings to separate lists in their machines would benefit from a general `sep` argument to be used for reading/storing csv files.

**Comment by jhmigueles** [comment]
Update on this: For now, I have looked for parts of the code in which a csv file is read or written by GGIR and implemented the argument `sep`. This includes reading accelerometer raw data csv files, read.myacc.csv, and all the logs that can be read by GGIR (sleeplog, activity log, data cleaning file, etc).

I'm afraid that the separator might not be consistent in some countries in Europe, for example, the separator for the logs might be by default ";" in Spain, but the separator used when downloading a csv raw data file from other brand-specific software might be hardcoded to ",". I know that actilife uses the machine default to export csv files, but I have no idea about others (e.g., axivity csv, genea csv, adhoc csv files exported by other brands). Do you think that including this argument can be problematic in these cases?

**Comment by vincentvanhees** [comment]
Can we keep it simple and only do this for writing csv files? For example, with a new argument `sep_csv_write`.

For reading accelerometer- or diary csv files I think we should not change anything, because this has been working fine for years. Changing it will introduce risk for many errors and user-questions.

**Comment by jhmigueles** [comment]
Sounds good for reading accelerometer files, I think it is better not to change that. For reading diaries, GGIR actually has this option for the sleeplog (`sleeplogsep`), but not for the other diaries. Should we be consistent and offer the option for all the diaries? Maybe `sep_csv_read_logs`?

**Comment by vincentvanhees** [comment]
Good idea, so conclusion:

For now we only do:
- sep_logs
- sep_reports

Maybe in the future:
- sep_acc => for csv accelerometer data

**Comment by jhmigueles** [comment]
Update on progress in this branch.

**sep_logs** implemented in: 
- sleep log
- activity log
- csv with calibration coefficients
- TimeSegments2ZeroFile
- Data cleaning file

**sep_reports** implemented in: 
- reports stored in results folder (including data_quality_report and all part 2, 4 and 5 reports)
- Timeseries stored in csv in part 2 and part 5
- Legend file for timeseries in part 5
- SIB report

**To think about**
g.plot5 loads the previously-generated reports, which used to be stored with sep = ",".  If now the user can change this to any other sep, g.plot5 will not be able to load such reports.
`sep_logs` is not appropriate to handle this as the reports are not logs, and `sep_reports` is intended to be
used when writing new reports, not when reading reports... So, what should we use? Or do we need another sep for this?

**Maybe in the future:**
- sep_acc => for csv accelerometer data
- sep_config?

**Comment by vincentvanhees** [comment]
Thanks, yes, sep_config would be good too.
