### ISSUE TITLE
EN en consistency

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#816]
Following on from comment by @jhmigueles [here](https://github.com/wadpac/GGIR/pull/809#discussion_r1239646983):

The column for Euclidian Norm in metalong object is not consistent in case across sensor brands: https://github.com/wadpac/GGIR/blob/master/R/g.getmeta.R#L351-L357. For some brands we use `EN` and for other `en`.

This would for example address the issue of not being able to process multiple brands at the same time for at least some combinations of brands: https://groups.google.com/g/RpackageGGIR/c/gSihX0GcrV8/m/AXTIBUsTAAAJ

Proposal:
- [ ] Make sure elsewhere in GGIR this case difference is ignored, for example when data is appended or when code tries to identify this column.
- [x] Update `en` to `EN` in function g.getmeta().

The result should be that all new output will have `EN` while GGIR can still handle previously processed `en` data.

**Comment by l-k-** [comment]
PR #1027 updates g.getmeta() to always use uppercase EN, here's the relevant commit: https://github.com/wadpac/GGIR/pull/1027/commits/579f3ac1c5c6e9981cb2a526f09074ad53c548c6
