### ISSUE TITLE
leading zero in sleeplog times: warn or enhance code to handle this?

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#851]
See discussion: https://groups.google.com/g/RpackageGGIR/c/pX4FEKQ8AlE/m/OtMh6ZPvBQAJ

Ideal solution would be that code automatically recognises when timestamps have no leading zero (6:30:00 instead of 06:30:00) and corrects for this.

**Comment by jhmigueles** [comment]
I tried to replicated this as part of the work in [PR 868](https://github.com/wadpac/GGIR/pull/868), but my sleeplog was read without any problem even if timestamps had no leading zeroes.

**Comment by vincentvanhees** [comment]
Closing this issue as issue seems fixed?
