### ISSUE TITLE
Minor bugs introduced in previous PR related to nnights

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#867]
In g.loadlog, there is a misplaced parenthesis in line 10 when automatically defining nnights: `nnights = floor((ncol(S) - coln1 + 1)) / 2` should be `nnights = floor((ncol(S) - coln1 + 1) / 2)`. So that uneven number of columns does not produced decimal places in nnights.

Additionally, when number of rows in sleeplog is lower than number of recordings, the sleeplog matrix produced in lines 206:207 of `g.loadlog` might be short and then trigger an "subscript out of bounds" error.

**Comment by vincentvanhees** [comment]
this relates to PR #861 that was merged yesterday.
