### ISSUE TITLE
g.part4 fails defining sleep period time for day sleepers

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#91]
Hello,

I noticed that g.part4 fails when defining sleep period time (SPT) for those participants wakening-up after 12pm (daysleepers).

I've been having a look at the code but I didn't managed to get the correct SPT detection for those participants. Here a summary of what I found:

In the second iteration of the loop through "loaddays" for daysleepers, the line "else if (loaddaysi == 2 & length(spo_day) > 0)" is impossible to produce a TRUE value for this conditional since the unique spo_day definition in the code is: "spo_day = c()".

When removing this conditional, I've been trying to change some parts of the code, but I've not been successful. Vincent, if you or anyone find the time to have a look on this funtion would be great, otherwise, I will try again when I find the time.

Best,
Jairo

**Comment by vincentvanhees** [comment]
thanks for the reminder Jairo, I have now fixed this. The bug was introduced in version 1.5-21 and only affects the daysleepers.
