### ISSUE TITLE
Actigraph csv files identified as Axivity csv.

### ISSUE THREAD

**Issue by l-k-** [wadpac/GGIR#918]
**Describe the bug**
(At least some) Actigraph csv files get mistakenly identified as Axivity csv, and then their processing errors out because the file format isn't as expected for an Axivity csv.

I'm sending a PR with a test that shows this, and a proposed fix. 

I only tested with https://github.com/wadpac/GGIR/blob/master/inst/testfiles/ActiGraph13.csv and https://github.com/wadpac/GGIR/blob/master/inst/testfiles/ActiGraph61.csv because I don't have access to any other Actigraph CSVs. I can do more testing if someone sends me more files.

- [X ] Have you tried this on the latest `master` branch from GitHub?

**Comment by vincentvanhees** [comment]
Closing because now merged in Master branch.
