### ISSUE TITLE
Error generating part2 reports when using older meta files from Axivity AX3 devices in version 3.0-0 and 2.9-0

### ISSUE THREAD

**Issue by Maylor8** [wadpac/GGIR#951]
**Describe the bug**
Generating new part2 meta files and reports using older part1 meta files from an Axivity produces this error message:

>Part 2 
 Busy processing ... see D:/Alex/output_data/meta/ms2.out for progress
___________________________________________________________________________________________________________________________________________________________________________________
>Report part 2 
 1 2Error in names(x) <- value : 
  'names' attribute [36] must be the same length as the vector [35]
In addition: Warning messages:
1: package ‘GGIR’ was built under R version 4.2.3 
2: In colnames(QCout)[newcols] <- newcolnames :
  number of items to replace is not a multiple of replacement length```
>
This error occurs in versions 3.0-0 and 2.10-1 but not 2.9-0 and older. we are also running the same script on meta files from GENEActiv and ActiGraph processed at teh same time, but the only issue has been with Axivity meta files.
[example cwa meta file.zip](https://github.com/wadpac/GGIR/files/13112930/example.cwa.meta.file.zip)
It seems that Vincent has tried to prevent this previously here: https://github.com/wadpac/GGIR/commit/62d6de0f6dfa022c324bd0d16be82ae7cd8ba66b

Here is one of the meta files

**To Reproduce**
Take the meta/basic files from older processed Axivity data, and re-run part 2 in versions 2.10-1 or 3.0 (example meta file attached)

1. Sensor brand: 'Axivity AX3'
3. Approximate recording duration 7 days
4. Are you using a sleep diary to guide the sleep detection:  NO
5. Copy of R command used: 'attached'
7. Have you tried processing your data based on GGIR's default argument values? Does the issue you report still appear? YES

**Expected behavior**
Part 2 to generate as normal, as per previous working in version 2.9.

**Screenshots**
If applicable, add screenshots to help explain your problem. Note that usually we are not only interested in see the error message in red, but all GGIR output to the console.

**Desktop (please complete the following information):**
 - OS: Windows 11: Version 10.0.22621 Build 22621
 - GGIR Version 3.0-0, but the issue also happens in 2.10-1, but not 2.9-0

**Additional context**
None

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there? reproduced on my pc as well as @alex-row on a different pc using Windows 10
- [x] Have you tried this on the latest `master` branch from GitHub? Yes, using the latest branch the error still occurs.
[example cwa meta file.zip](https://github.com/wadpac/GGIR/files/13112930/example.cwa.meta.file.zip)

**Comment by Maylor8** [comment]
apologies - the meta files for the Axivity were generated using version 3.0-0, not an older version of GGIR.

**Comment by vincentvanhees** [comment]
This may relate to the issue that PR 947 tries to fix: https://github.com/wadpac/GGIR/pull/947

Could you try their branch?
`remotes::install_github("zcx980605/GGIR", ref = "fix_typo_in_g.report.part2")`

**Comment by Maylor8** [comment]
@vincentvanhees Thanks, using that version worked ok and results look as expected.

**Comment by vincentvanhees** [comment]
Great, thanks for confirming. I will close this issue, feel free to re-open if the problem returns.
