### ISSUE TITLE
Overlapping of 1 second when combining chunks of data in g.getmeta

### ISSUE THREAD

**Issue by jhmigueles** [wadpac/GGIR#952]
While working on the issue #571, I have noticed that there is an overlap of 1 second in every block that is read using gt3x files (now testing in files from other brands). 

`g.getmeta` selects the data to be analyzed in each chunk and stores the remaining data to be appended to the next chunk in the object `S`. The last second in `S` is repeated as the first second in the next chunk, and, when combining the objects, there is a repetition of this second in the time series. 

Below a plot to visualize this showing the part of the timeseries in which the chunks have been appended:
![image](https://github.com/wadpac/GGIR/assets/28734336/c6f4c8e6-13b6-47e9-b75d-81bc71fed132)

**Comment by jhmigueles** [comment]
**Update:** It seems this only occurs with gt3x files

**Comment by vincentvanhees** [comment]
gt3x data is read by selecting it in chunks (batch_begin, batch_end) which length is defined in seconds. So, I maybe something goes wrong with incrementing the start and end of each chunk. For example, code does 1-11, 11-21, not realising that 11 is included in both?
