### ISSUE TITLE
Parallel error  when processing cwa data

### ISSUE THREAD

**Issue by rui4833** [wadpac/GGIR#977]
I was processing cwa data from UK Biobank. The available core number of the server I used was 72, I also set do.parallel=T. I want to process faster, so I tried both snowfall package and shell script provided by the vignettes. Then I met this error: "Cluster setup failed. 31 of 71 workers failed to connect."

I wonder if there is a better way to solve this.

Thank you so much for your time to help me solve this question.

**Comment by vincentvanhees** [comment]
GGIR uses the R package foreach to utilise multiple cores of the machine it is running on. 

When running GGIR on a cluster I use bash scripts to start a separate GGIR process on each node of the cluster, each processing their own sub dataset. See also the [brief explanation](https://cran.r-project.org/web/packages/GGIR/vignettes/GGIR.html#32_In_a_cluster) I included in the vignette.

I have no experience with snowfall, but I suppose snowfall does not like it that foreach is also trying to use multiple cores by which setting `do.parallel = FALSE` may be needed.

**Comment by rui4833** [comment]
thank you
