### ISSUE TITLE
GGIR algorithm, sliding window statistics or patterns

### ISSUE THREAD

**Issue by prinsherbert** [wadpac/GGIR#98]
I was wondering what GGIR's algorithm is. The image below [from here](https://cran.r-project.org/web/packages/GGIR/vignettes/GGIR.html ) suggests GGIR thresholds the variance within a sliding window of the arm angle and the arm movement to detect sleep.

I am unfamiliar with R, hence I had a hard time reading the code.

Does GGIR look

- at statistics of a sliding window, or
- does it also learn patterns (read convolution), or
- does it do something else?

Would GGIR be suited for other classifications, like walking, cycling, fishing, etc?

![ggir](https://user-images.githubusercontent.com/7011110/41776170-fc8d3d0c-7626-11e8-8391-4d49ce272da6.png)

**Comment by vincentvanhees** [comment]
Hi, what the package does is described in open access journal publications as referenced in the tutorial and vignette (2015 paper). These are heuristic classificatiers (no machine learning). Please note that GGIR generates the signal features that could in theory be used as input for machine learning. I hope that clarifies your question.
